app:
  name: "report-svc"
  env: "dev"

log:
  level: "debug"

otel:
  endpoint: "otel-collector:4317"
  insecure: true
  metrics_export_interval: 10s
  runtime_read_mem_stats_interval: 10s

grpc:
  addr: "0.0.0.0:8098"

http:
  addr: "0.0.0.0:8099"
  shutdown_timeout: 5s

minio:
  endpoint: "minio:9000"
  bucket: "tax-reports"
  use_ssl: false
