stages:
  - lint
  - test
  - build

variables:
  GOWORK: "on"
  GOPATH: "$CI_PROJECT_DIR/.go"
  GOCACHE: "$CI_PROJECT_DIR/.cache/go-build"
  GOMODCACHE: "$CI_PROJECT_DIR/.cache/go-mod"

cache:
  key: "${CI_COMMIT_REF_SLUG}"
  paths:
    - .cache/go-build
    - .cache/go-mod

lint:
  image: golangci/golangci-lint:v1.64
  stage: lint
  script:
    - golangci-lint version
    - golangci-lint run ./...
  rules:
    - if: $CI_PIPELINE_SOURCE == "merge_request_event"
    - if: $CI_COMMIT_BRANCH

unit-test:
  image: golang:1.25
  stage: test
  script:
    - go version
    - go test ./...
  rules:
    - if: $CI_PIPELINE_SOURCE == "merge_request_event"
    - if: $CI_COMMIT_BRANCH

build:
  image: golang:1.25
  stage: build
  script:
    - go version
    - go build ./...
  rules:
    - if: $CI_PIPELINE_SOURCE == "merge_request_event"
    - if: $CI_COMMIT_BRANCH
