// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/NightRunner/CryptoTax-Go/services/price-svc/internal/domain (interfaces: HistoricalPriceRepo,TenantSymbolRepo)
//
// Generated by this command:
//
//	mockgen -destination=repo_mocks.gen.go -package=mocks github.com/NightRunner/CryptoTax-Go/services/price-svc/internal/domain HistoricalPriceRepo,TenantSymbolRepo
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"
	time "time"

	domain "github.com/NightRunner/CryptoTax-Go/services/price-svc/internal/domain"
	uuid "github.com/google/uuid"
	gomock "go.uber.org/mock/gomock"
)

// MockHistoricalPriceRepo is a mock of HistoricalPriceRepo interface.
type MockHistoricalPriceRepo struct {
	ctrl     *gomock.Controller
	recorder *MockHistoricalPriceRepoMockRecorder
	isgomock struct{}
}

// MockHistoricalPriceRepoMockRecorder is the mock recorder for MockHistoricalPriceRepo.
type MockHistoricalPriceRepoMockRecorder struct {
	mock *MockHistoricalPriceRepo
}

// NewMockHistoricalPriceRepo creates a new mock instance.
func NewMockHistoricalPriceRepo(ctrl *gomock.Controller) *MockHistoricalPriceRepo {
	mock := &MockHistoricalPriceRepo{ctrl: ctrl}
	mock.recorder = &MockHistoricalPriceRepoMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockHistoricalPriceRepo) EXPECT() *MockHistoricalPriceRepoMockRecorder {
	return m.recorder
}

// Get mocks base method.
func (m *MockHistoricalPriceRepo) Get(ctx context.Context, coinID string, bucketStartUtc time.Time) (domain.HistoricalPrice, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Get", ctx, coinID, bucketStartUtc)
	ret0, _ := ret[0].(domain.HistoricalPrice)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Get indicates an expected call of Get.
func (mr *MockHistoricalPriceRepoMockRecorder) Get(ctx, coinID, bucketStartUtc any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Get", reflect.TypeOf((*MockHistoricalPriceRepo)(nil).Get), ctx, coinID, bucketStartUtc)
}

// GetBatch mocks base method.
func (m *MockHistoricalPriceRepo) GetBatch(ctx context.Context, priceKeys []domain.PriceKey) ([]domain.HistoricalPrice, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetBatch", ctx, priceKeys)
	ret0, _ := ret[0].([]domain.HistoricalPrice)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetBatch indicates an expected call of GetBatch.
func (mr *MockHistoricalPriceRepoMockRecorder) GetBatch(ctx, priceKeys any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetBatch", reflect.TypeOf((*MockHistoricalPriceRepo)(nil).GetBatch), ctx, priceKeys)
}

// Upsert mocks base method.
func (m *MockHistoricalPriceRepo) Upsert(ctx context.Context, p domain.HistoricalPrice) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Upsert", ctx, p)
	ret0, _ := ret[0].(error)
	return ret0
}

// Upsert indicates an expected call of Upsert.
func (mr *MockHistoricalPriceRepoMockRecorder) Upsert(ctx, p any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Upsert", reflect.TypeOf((*MockHistoricalPriceRepo)(nil).Upsert), ctx, p)
}

// UpsertBatch mocks base method.
func (m *MockHistoricalPriceRepo) UpsertBatch(ctx context.Context, prices []domain.HistoricalPrice) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpsertBatch", ctx, prices)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpsertBatch indicates an expected call of UpsertBatch.
func (mr *MockHistoricalPriceRepoMockRecorder) UpsertBatch(ctx, prices any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpsertBatch", reflect.TypeOf((*MockHistoricalPriceRepo)(nil).UpsertBatch), ctx, prices)
}

// MockTenantSymbolRepo is a mock of TenantSymbolRepo interface.
type MockTenantSymbolRepo struct {
	ctrl     *gomock.Controller
	recorder *MockTenantSymbolRepoMockRecorder
	isgomock struct{}
}

// MockTenantSymbolRepoMockRecorder is the mock recorder for MockTenantSymbolRepo.
type MockTenantSymbolRepoMockRecorder struct {
	mock *MockTenantSymbolRepo
}

// NewMockTenantSymbolRepo creates a new mock instance.
func NewMockTenantSymbolRepo(ctrl *gomock.Controller) *MockTenantSymbolRepo {
	mock := &MockTenantSymbolRepo{ctrl: ctrl}
	mock.recorder = &MockTenantSymbolRepoMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockTenantSymbolRepo) EXPECT() *MockTenantSymbolRepoMockRecorder {
	return m.recorder
}

// Delete mocks base method.
func (m *MockTenantSymbolRepo) Delete(ctx context.Context, tenantID uuid.UUID, source, symbol string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", ctx, tenantID, source, symbol)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *MockTenantSymbolRepoMockRecorder) Delete(ctx, tenantID, source, symbol any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockTenantSymbolRepo)(nil).Delete), ctx, tenantID, source, symbol)
}

// GetList mocks base method.
func (m *MockTenantSymbolRepo) GetList(ctx context.Context, tenantID uuid.UUID, source string, symbols []string) ([]domain.TenantSymbol, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetList", ctx, tenantID, source, symbols)
	ret0, _ := ret[0].([]domain.TenantSymbol)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetList indicates an expected call of GetList.
func (mr *MockTenantSymbolRepoMockRecorder) GetList(ctx, tenantID, source, symbols any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetList", reflect.TypeOf((*MockTenantSymbolRepo)(nil).GetList), ctx, tenantID, source, symbols)
}

// GetListBySource mocks base method.
func (m *MockTenantSymbolRepo) GetListBySource(ctx context.Context, tenantID uuid.UUID, source string) ([]domain.TenantSymbol, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetListBySource", ctx, tenantID, source)
	ret0, _ := ret[0].([]domain.TenantSymbol)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetListBySource indicates an expected call of GetListBySource.
func (mr *MockTenantSymbolRepoMockRecorder) GetListBySource(ctx, tenantID, source any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetListBySource", reflect.TypeOf((*MockTenantSymbolRepo)(nil).GetListBySource), ctx, tenantID, source)
}

// Upsert mocks base method.
func (m *MockTenantSymbolRepo) Upsert(ctx context.Context, s domain.TenantSymbol) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Upsert", ctx, s)
	ret0, _ := ret[0].(error)
	return ret0
}

// Upsert indicates an expected call of Upsert.
func (mr *MockTenantSymbolRepoMockRecorder) Upsert(ctx, s any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Upsert", reflect.TypeOf((*MockTenantSymbolRepo)(nil).Upsert), ctx, s)
}
