// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/NightRunner/CryptoTax-Go/services/price-svc/internal/domain (interfaces: HistoricalPriceUseCase,FXProvider,CoinIdResolver,UserSymbolUseCase)
//
// Generated by this command:
//
//	mockgen -destination=usecase_mocks.gen.go -package=mocks github.com/NightRunner/CryptoTax-Go/services/price-svc/internal/domain HistoricalPriceUseCase,FXProvider,CoinIdResolver,UserSymbolUseCase
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"
	time "time"

	domain "github.com/NightRunner/CryptoTax-Go/services/price-svc/internal/domain"
	uuid "github.com/google/uuid"
	gomock "go.uber.org/mock/gomock"
)

// MockHistoricalPriceUseCase is a mock of HistoricalPriceUseCase interface.
type MockHistoricalPriceUseCase struct {
	ctrl     *gomock.Controller
	recorder *MockHistoricalPriceUseCaseMockRecorder
	isgomock struct{}
}

// MockHistoricalPriceUseCaseMockRecorder is the mock recorder for MockHistoricalPriceUseCase.
type MockHistoricalPriceUseCaseMockRecorder struct {
	mock *MockHistoricalPriceUseCase
}

// NewMockHistoricalPriceUseCase creates a new mock instance.
func NewMockHistoricalPriceUseCase(ctrl *gomock.Controller) *MockHistoricalPriceUseCase {
	mock := &MockHistoricalPriceUseCase{ctrl: ctrl}
	mock.recorder = &MockHistoricalPriceUseCaseMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockHistoricalPriceUseCase) EXPECT() *MockHistoricalPriceUseCaseMockRecorder {
	return m.recorder
}

// GetHistoricalPrices mocks base method.
func (m *MockHistoricalPriceUseCase) GetHistoricalPrices(ctx context.Context, fiatCurrency string, priceKeys []domain.PriceKey) ([]domain.Fiat, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetHistoricalPrices", ctx, fiatCurrency, priceKeys)
	ret0, _ := ret[0].([]domain.Fiat)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetHistoricalPrices indicates an expected call of GetHistoricalPrices.
func (mr *MockHistoricalPriceUseCaseMockRecorder) GetHistoricalPrices(ctx, fiatCurrency, priceKeys any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetHistoricalPrices", reflect.TypeOf((*MockHistoricalPriceUseCase)(nil).GetHistoricalPrices), ctx, fiatCurrency, priceKeys)
}

// MockFXProvider is a mock of FXProvider interface.
type MockFXProvider struct {
	ctrl     *gomock.Controller
	recorder *MockFXProviderMockRecorder
	isgomock struct{}
}

// MockFXProviderMockRecorder is the mock recorder for MockFXProvider.
type MockFXProviderMockRecorder struct {
	mock *MockFXProvider
}

// NewMockFXProvider creates a new mock instance.
func NewMockFXProvider(ctrl *gomock.Controller) *MockFXProvider {
	mock := &MockFXProvider{ctrl: ctrl}
	mock.recorder = &MockFXProviderMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockFXProvider) EXPECT() *MockFXProviderMockRecorder {
	return m.recorder
}

// GetUSDtoFiatRate mocks base method.
func (m *MockFXProvider) GetUSDtoFiatRate(ctx context.Context, day time.Time, fiat string) (domain.Fiat, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetUSDtoFiatRate", ctx, day, fiat)
	ret0, _ := ret[0].(domain.Fiat)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetUSDtoFiatRate indicates an expected call of GetUSDtoFiatRate.
func (mr *MockFXProviderMockRecorder) GetUSDtoFiatRate(ctx, day, fiat any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetUSDtoFiatRate", reflect.TypeOf((*MockFXProvider)(nil).GetUSDtoFiatRate), ctx, day, fiat)
}

// Start mocks base method.
func (m *MockFXProvider) Start(arg0 context.Context) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Start", arg0)
	ret0, _ := ret[0].(error)
	return ret0
}

// Start indicates an expected call of Start.
func (mr *MockFXProviderMockRecorder) Start(arg0 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Start", reflect.TypeOf((*MockFXProvider)(nil).Start), arg0)
}

// Stop mocks base method.
func (m *MockFXProvider) Stop(arg0 context.Context) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Stop", arg0)
	ret0, _ := ret[0].(error)
	return ret0
}

// Stop indicates an expected call of Stop.
func (mr *MockFXProviderMockRecorder) Stop(arg0 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Stop", reflect.TypeOf((*MockFXProvider)(nil).Stop), arg0)
}

// MockCoinIdResolver is a mock of CoinIdResolver interface.
type MockCoinIdResolver struct {
	ctrl     *gomock.Controller
	recorder *MockCoinIdResolverMockRecorder
	isgomock struct{}
}

// MockCoinIdResolverMockRecorder is the mock recorder for MockCoinIdResolver.
type MockCoinIdResolverMockRecorder struct {
	mock *MockCoinIdResolver
}

// NewMockCoinIdResolver creates a new mock instance.
func NewMockCoinIdResolver(ctrl *gomock.Controller) *MockCoinIdResolver {
	mock := &MockCoinIdResolver{ctrl: ctrl}
	mock.recorder = &MockCoinIdResolverMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockCoinIdResolver) EXPECT() *MockCoinIdResolverMockRecorder {
	return m.recorder
}

// Resolve mocks base method.
func (m *MockCoinIdResolver) Resolve(symbol string) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Resolve", symbol)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Resolve indicates an expected call of Resolve.
func (mr *MockCoinIdResolverMockRecorder) Resolve(symbol any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Resolve", reflect.TypeOf((*MockCoinIdResolver)(nil).Resolve), symbol)
}

// MockUserSymbolUseCase is a mock of UserSymbolUseCase interface.
type MockUserSymbolUseCase struct {
	ctrl     *gomock.Controller
	recorder *MockUserSymbolUseCaseMockRecorder
	isgomock struct{}
}

// MockUserSymbolUseCaseMockRecorder is the mock recorder for MockUserSymbolUseCase.
type MockUserSymbolUseCaseMockRecorder struct {
	mock *MockUserSymbolUseCase
}

// NewMockUserSymbolUseCase creates a new mock instance.
func NewMockUserSymbolUseCase(ctrl *gomock.Controller) *MockUserSymbolUseCase {
	mock := &MockUserSymbolUseCase{ctrl: ctrl}
	mock.recorder = &MockUserSymbolUseCaseMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockUserSymbolUseCase) EXPECT() *MockUserSymbolUseCaseMockRecorder {
	return m.recorder
}

// Delete mocks base method.
func (m *MockUserSymbolUseCase) Delete(ctx context.Context, userID uuid.UUID, source, symbol string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", ctx, userID, source, symbol)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *MockUserSymbolUseCaseMockRecorder) Delete(ctx, userID, source, symbol any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockUserSymbolUseCase)(nil).Delete), ctx, userID, source, symbol)
}

// GetList mocks base method.
func (m *MockUserSymbolUseCase) GetList(ctx context.Context, userID uuid.UUID, source string, symbols []string) ([]domain.UserSymbol, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetList", ctx, userID, source, symbols)
	ret0, _ := ret[0].([]domain.UserSymbol)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetList indicates an expected call of GetList.
func (mr *MockUserSymbolUseCaseMockRecorder) GetList(ctx, userID, source, symbols any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetList", reflect.TypeOf((*MockUserSymbolUseCase)(nil).GetList), ctx, userID, source, symbols)
}

// GetListBySource mocks base method.
func (m *MockUserSymbolUseCase) GetListBySource(ctx context.Context, userID uuid.UUID, source string) ([]domain.UserSymbol, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetListBySource", ctx, userID, source)
	ret0, _ := ret[0].([]domain.UserSymbol)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetListBySource indicates an expected call of GetListBySource.
func (mr *MockUserSymbolUseCaseMockRecorder) GetListBySource(ctx, userID, source any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetListBySource", reflect.TypeOf((*MockUserSymbolUseCase)(nil).GetListBySource), ctx, userID, source)
}

// Upsert mocks base method.
func (m *MockUserSymbolUseCase) Upsert(ctx context.Context, s domain.UserSymbol) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Upsert", ctx, s)
	ret0, _ := ret[0].(error)
	return ret0
}

// Upsert indicates an expected call of Upsert.
func (mr *MockUserSymbolUseCaseMockRecorder) Upsert(ctx, s any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Upsert", reflect.TypeOf((*MockUserSymbolUseCase)(nil).Upsert), ctx, s)
}
