// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/NightRunner/CryptoTax-Go/services/tax-svc/db/sqlc (interfaces: Store)
//
// Generated by this command:
//
//	mockgen -destination=repo_store_mocks.gen.go -package=mocks github.com/NightRunner/CryptoTax-Go/services/tax-svc/db/sqlc Store
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	db "github.com/NightRunner/CryptoTax-Go/services/tax-svc/db/sqlc"
	uuid "github.com/google/uuid"
	gomock "go.uber.org/mock/gomock"
)

// MockStore is a mock of Store interface.
type MockStore struct {
	ctrl     *gomock.Controller
	recorder *MockStoreMockRecorder
	isgomock struct{}
}

// MockStoreMockRecorder is the mock recorder for MockStore.
type MockStoreMockRecorder struct {
	mock *MockStore
}

// NewMockStore creates a new mock instance.
func NewMockStore(ctrl *gomock.Controller) *MockStore {
	mock := &MockStore{ctrl: ctrl}
	mock.recorder = &MockStoreMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockStore) EXPECT() *MockStoreMockRecorder {
	return m.recorder
}

// ClaimNextQueuedTaxJob mocks base method.
func (m *MockStore) ClaimNextQueuedTaxJob(ctx context.Context) (db.TaxJob, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ClaimNextQueuedTaxJob", ctx)
	ret0, _ := ret[0].(db.TaxJob)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ClaimNextQueuedTaxJob indicates an expected call of ClaimNextQueuedTaxJob.
func (mr *MockStoreMockRecorder) ClaimNextQueuedTaxJob(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ClaimNextQueuedTaxJob", reflect.TypeOf((*MockStore)(nil).ClaimNextQueuedTaxJob), ctx)
}

// CountTaxJobs mocks base method.
func (m *MockStore) CountTaxJobs(ctx context.Context, tenantID uuid.UUID) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CountTaxJobs", ctx, tenantID)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CountTaxJobs indicates an expected call of CountTaxJobs.
func (mr *MockStoreMockRecorder) CountTaxJobs(ctx, tenantID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CountTaxJobs", reflect.TypeOf((*MockStore)(nil).CountTaxJobs), ctx, tenantID)
}

// CreateTaxJob mocks base method.
func (m *MockStore) CreateTaxJob(ctx context.Context, arg db.CreateTaxJobParams) (db.TaxJob, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateTaxJob", ctx, arg)
	ret0, _ := ret[0].(db.TaxJob)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateTaxJob indicates an expected call of CreateTaxJob.
func (mr *MockStoreMockRecorder) CreateTaxJob(ctx, arg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateTaxJob", reflect.TypeOf((*MockStore)(nil).CreateTaxJob), ctx, arg)
}

// DeleteTaxProfile mocks base method.
func (m *MockStore) DeleteTaxProfile(ctx context.Context, tenantID uuid.UUID) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteTaxProfile", ctx, tenantID)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// DeleteTaxProfile indicates an expected call of DeleteTaxProfile.
func (mr *MockStoreMockRecorder) DeleteTaxProfile(ctx, tenantID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteTaxProfile", reflect.TypeOf((*MockStore)(nil).DeleteTaxProfile), ctx, tenantID)
}

// ExecTx mocks base method.
func (m *MockStore) ExecTx(ctx context.Context, fn func(*db.Queries) error) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ExecTx", ctx, fn)
	ret0, _ := ret[0].(error)
	return ret0
}

// ExecTx indicates an expected call of ExecTx.
func (mr *MockStoreMockRecorder) ExecTx(ctx, fn any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ExecTx", reflect.TypeOf((*MockStore)(nil).ExecTx), ctx, fn)
}

// GetTaxJob mocks base method.
func (m *MockStore) GetTaxJob(ctx context.Context, arg db.GetTaxJobParams) (db.TaxJob, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetTaxJob", ctx, arg)
	ret0, _ := ret[0].(db.TaxJob)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetTaxJob indicates an expected call of GetTaxJob.
func (mr *MockStoreMockRecorder) GetTaxJob(ctx, arg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetTaxJob", reflect.TypeOf((*MockStore)(nil).GetTaxJob), ctx, arg)
}

// GetTaxProfile mocks base method.
func (m *MockStore) GetTaxProfile(ctx context.Context, tenantID uuid.UUID) (db.TaxProfile, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetTaxProfile", ctx, tenantID)
	ret0, _ := ret[0].(db.TaxProfile)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetTaxProfile indicates an expected call of GetTaxProfile.
func (mr *MockStoreMockRecorder) GetTaxProfile(ctx, tenantID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetTaxProfile", reflect.TypeOf((*MockStore)(nil).GetTaxProfile), ctx, tenantID)
}

// ListTaxJobs mocks base method.
func (m *MockStore) ListTaxJobs(ctx context.Context, arg db.ListTaxJobsParams) ([]db.TaxJob, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListTaxJobs", ctx, arg)
	ret0, _ := ret[0].([]db.TaxJob)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListTaxJobs indicates an expected call of ListTaxJobs.
func (mr *MockStoreMockRecorder) ListTaxJobs(ctx, arg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListTaxJobs", reflect.TypeOf((*MockStore)(nil).ListTaxJobs), ctx, arg)
}

// MarkTaxJobCanceled mocks base method.
func (m *MockStore) MarkTaxJobCanceled(ctx context.Context, id uuid.UUID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "MarkTaxJobCanceled", ctx, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// MarkTaxJobCanceled indicates an expected call of MarkTaxJobCanceled.
func (mr *MockStoreMockRecorder) MarkTaxJobCanceled(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "MarkTaxJobCanceled", reflect.TypeOf((*MockStore)(nil).MarkTaxJobCanceled), ctx, id)
}

// MarkTaxJobFailed mocks base method.
func (m *MockStore) MarkTaxJobFailed(ctx context.Context, arg db.MarkTaxJobFailedParams) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "MarkTaxJobFailed", ctx, arg)
	ret0, _ := ret[0].(error)
	return ret0
}

// MarkTaxJobFailed indicates an expected call of MarkTaxJobFailed.
func (mr *MockStoreMockRecorder) MarkTaxJobFailed(ctx, arg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "MarkTaxJobFailed", reflect.TypeOf((*MockStore)(nil).MarkTaxJobFailed), ctx, arg)
}

// RequeueTaxJob mocks base method.
func (m *MockStore) RequeueTaxJob(ctx context.Context, arg db.RequeueTaxJobParams) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RequeueTaxJob", ctx, arg)
	ret0, _ := ret[0].(error)
	return ret0
}

// RequeueTaxJob indicates an expected call of RequeueTaxJob.
func (mr *MockStoreMockRecorder) RequeueTaxJob(ctx, arg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RequeueTaxJob", reflect.TypeOf((*MockStore)(nil).RequeueTaxJob), ctx, arg)
}

// SaveTaxJobResult mocks base method.
func (m *MockStore) SaveTaxJobResult(ctx context.Context, arg db.SaveTaxJobResultParams) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SaveTaxJobResult", ctx, arg)
	ret0, _ := ret[0].(error)
	return ret0
}

// SaveTaxJobResult indicates an expected call of SaveTaxJobResult.
func (mr *MockStoreMockRecorder) SaveTaxJobResult(ctx, arg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SaveTaxJobResult", reflect.TypeOf((*MockStore)(nil).SaveTaxJobResult), ctx, arg)
}

// UpsertTaxProfile mocks base method.
func (m *MockStore) UpsertTaxProfile(ctx context.Context, arg db.UpsertTaxProfileParams) (db.TaxProfile, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpsertTaxProfile", ctx, arg)
	ret0, _ := ret[0].(db.TaxProfile)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpsertTaxProfile indicates an expected call of UpsertTaxProfile.
func (mr *MockStoreMockRecorder) UpsertTaxProfile(ctx, arg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpsertTaxProfile", reflect.TypeOf((*MockStore)(nil).UpsertTaxProfile), ctx, arg)
}
