// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/NightRunner/CryptoTax-Go/services/tax-svc/internal/domain (interfaces: TaxProfileUseCase,TaxJobUseCase)
//
// Generated by this command:
//
//	mockgen -destination=server_uc_mocks.gen.go -package=mocks github.com/NightRunner/CryptoTax-Go/services/tax-svc/internal/domain TaxProfileUseCase,TaxJobUseCase
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	domain "github.com/NightRunner/CryptoTax-Go/services/tax-svc/internal/domain"
	uuid "github.com/google/uuid"
	gomock "go.uber.org/mock/gomock"
)

// MockTaxProfileUseCase is a mock of TaxProfileUseCase interface.
type MockTaxProfileUseCase struct {
	ctrl     *gomock.Controller
	recorder *MockTaxProfileUseCaseMockRecorder
	isgomock struct{}
}

// MockTaxProfileUseCaseMockRecorder is the mock recorder for MockTaxProfileUseCase.
type MockTaxProfileUseCaseMockRecorder struct {
	mock *MockTaxProfileUseCase
}

// NewMockTaxProfileUseCase creates a new mock instance.
func NewMockTaxProfileUseCase(ctrl *gomock.Controller) *MockTaxProfileUseCase {
	mock := &MockTaxProfileUseCase{ctrl: ctrl}
	mock.recorder = &MockTaxProfileUseCaseMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockTaxProfileUseCase) EXPECT() *MockTaxProfileUseCaseMockRecorder {
	return m.recorder
}

// Delete mocks base method.
func (m *MockTaxProfileUseCase) Delete(ctx context.Context, userID uuid.UUID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", ctx, userID)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *MockTaxProfileUseCaseMockRecorder) Delete(ctx, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockTaxProfileUseCase)(nil).Delete), ctx, userID)
}

// Get mocks base method.
func (m *MockTaxProfileUseCase) Get(ctx context.Context, userID uuid.UUID) (domain.TaxProfile, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Get", ctx, userID)
	ret0, _ := ret[0].(domain.TaxProfile)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Get indicates an expected call of Get.
func (mr *MockTaxProfileUseCaseMockRecorder) Get(ctx, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Get", reflect.TypeOf((*MockTaxProfileUseCase)(nil).Get), ctx, userID)
}

// Upsert mocks base method.
func (m *MockTaxProfileUseCase) Upsert(ctx context.Context, p domain.TaxProfile) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Upsert", ctx, p)
	ret0, _ := ret[0].(error)
	return ret0
}

// Upsert indicates an expected call of Upsert.
func (mr *MockTaxProfileUseCaseMockRecorder) Upsert(ctx, p any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Upsert", reflect.TypeOf((*MockTaxProfileUseCase)(nil).Upsert), ctx, p)
}

// MockTaxJobUseCase is a mock of TaxJobUseCase interface.
type MockTaxJobUseCase struct {
	ctrl     *gomock.Controller
	recorder *MockTaxJobUseCaseMockRecorder
	isgomock struct{}
}

// MockTaxJobUseCaseMockRecorder is the mock recorder for MockTaxJobUseCase.
type MockTaxJobUseCaseMockRecorder struct {
	mock *MockTaxJobUseCase
}

// NewMockTaxJobUseCase creates a new mock instance.
func NewMockTaxJobUseCase(ctrl *gomock.Controller) *MockTaxJobUseCase {
	mock := &MockTaxJobUseCase{ctrl: ctrl}
	mock.recorder = &MockTaxJobUseCaseMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockTaxJobUseCase) EXPECT() *MockTaxJobUseCaseMockRecorder {
	return m.recorder
}

// Enqueue mocks base method.
func (m *MockTaxJobUseCase) Enqueue(ctx context.Context, userID uuid.UUID, taxYear int, taxPolicy domain.TaxPolicy) (domain.TaxJob, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Enqueue", ctx, userID, taxYear, taxPolicy)
	ret0, _ := ret[0].(domain.TaxJob)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Enqueue indicates an expected call of Enqueue.
func (mr *MockTaxJobUseCaseMockRecorder) Enqueue(ctx, userID, taxYear, taxPolicy any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Enqueue", reflect.TypeOf((*MockTaxJobUseCase)(nil).Enqueue), ctx, userID, taxYear, taxPolicy)
}

// GetStatus mocks base method.
func (m *MockTaxJobUseCase) GetStatus(ctx context.Context, userID, jobID uuid.UUID) (domain.TaxJob, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetStatus", ctx, userID, jobID)
	ret0, _ := ret[0].(domain.TaxJob)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetStatus indicates an expected call of GetStatus.
func (mr *MockTaxJobUseCaseMockRecorder) GetStatus(ctx, userID, jobID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetStatus", reflect.TypeOf((*MockTaxJobUseCase)(nil).GetStatus), ctx, userID, jobID)
}

// List mocks base method.
func (m *MockTaxJobUseCase) List(ctx context.Context, userID uuid.UUID, limit, offset int32) ([]domain.TaxJob, int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "List", ctx, userID, limit, offset)
	ret0, _ := ret[0].([]domain.TaxJob)
	ret1, _ := ret[1].(int64)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// List indicates an expected call of List.
func (mr *MockTaxJobUseCaseMockRecorder) List(ctx, userID, limit, offset any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "List", reflect.TypeOf((*MockTaxJobUseCase)(nil).List), ctx, userID, limit, offset)
}
