// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/NightRunner/CryptoTax-Go/services/tax-svc/internal/domain (interfaces: TaxProfileRepo,TaxJobRepo,ObjectStorage,AggregatedTxProvider,ReportClient)
//
// Generated by this command:
//
//	mockgen -destination=usecase_deps_mocks.gen.go -package=mocks github.com/NightRunner/CryptoTax-Go/services/tax-svc/internal/domain TaxProfileRepo,TaxJobRepo,ObjectStorage,AggregatedTxProvider,ReportClient
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"
	time "time"

	domain "github.com/NightRunner/CryptoTax-Go/services/tax-svc/internal/domain"
	uuid "github.com/google/uuid"
	gomock "go.uber.org/mock/gomock"
)

// MockTaxProfileRepo is a mock of TaxProfileRepo interface.
type MockTaxProfileRepo struct {
	ctrl     *gomock.Controller
	recorder *MockTaxProfileRepoMockRecorder
	isgomock struct{}
}

// MockTaxProfileRepoMockRecorder is the mock recorder for MockTaxProfileRepo.
type MockTaxProfileRepoMockRecorder struct {
	mock *MockTaxProfileRepo
}

// NewMockTaxProfileRepo creates a new mock instance.
func NewMockTaxProfileRepo(ctrl *gomock.Controller) *MockTaxProfileRepo {
	mock := &MockTaxProfileRepo{ctrl: ctrl}
	mock.recorder = &MockTaxProfileRepoMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockTaxProfileRepo) EXPECT() *MockTaxProfileRepoMockRecorder {
	return m.recorder
}

// Delete mocks base method.
func (m *MockTaxProfileRepo) Delete(ctx context.Context, userID uuid.UUID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", ctx, userID)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *MockTaxProfileRepoMockRecorder) Delete(ctx, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockTaxProfileRepo)(nil).Delete), ctx, userID)
}

// Get mocks base method.
func (m *MockTaxProfileRepo) Get(ctx context.Context, userID uuid.UUID) (domain.TaxProfile, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Get", ctx, userID)
	ret0, _ := ret[0].(domain.TaxProfile)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Get indicates an expected call of Get.
func (mr *MockTaxProfileRepoMockRecorder) Get(ctx, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Get", reflect.TypeOf((*MockTaxProfileRepo)(nil).Get), ctx, userID)
}

// Upsert mocks base method.
func (m *MockTaxProfileRepo) Upsert(ctx context.Context, p domain.TaxProfile) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Upsert", ctx, p)
	ret0, _ := ret[0].(error)
	return ret0
}

// Upsert indicates an expected call of Upsert.
func (mr *MockTaxProfileRepoMockRecorder) Upsert(ctx, p any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Upsert", reflect.TypeOf((*MockTaxProfileRepo)(nil).Upsert), ctx, p)
}

// MockTaxJobRepo is a mock of TaxJobRepo interface.
type MockTaxJobRepo struct {
	ctrl     *gomock.Controller
	recorder *MockTaxJobRepoMockRecorder
	isgomock struct{}
}

// MockTaxJobRepoMockRecorder is the mock recorder for MockTaxJobRepo.
type MockTaxJobRepoMockRecorder struct {
	mock *MockTaxJobRepo
}

// NewMockTaxJobRepo creates a new mock instance.
func NewMockTaxJobRepo(ctrl *gomock.Controller) *MockTaxJobRepo {
	mock := &MockTaxJobRepo{ctrl: ctrl}
	mock.recorder = &MockTaxJobRepoMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockTaxJobRepo) EXPECT() *MockTaxJobRepoMockRecorder {
	return m.recorder
}

// ClaimNextQueued mocks base method.
func (m *MockTaxJobRepo) ClaimNextQueued(ctx context.Context) (*domain.TaxJob, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ClaimNextQueued", ctx)
	ret0, _ := ret[0].(*domain.TaxJob)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ClaimNextQueued indicates an expected call of ClaimNextQueued.
func (mr *MockTaxJobRepoMockRecorder) ClaimNextQueued(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ClaimNextQueued", reflect.TypeOf((*MockTaxJobRepo)(nil).ClaimNextQueued), ctx)
}

// Create mocks base method.
func (m *MockTaxJobRepo) Create(ctx context.Context, job domain.TaxJob) (domain.TaxJob, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, job)
	ret0, _ := ret[0].(domain.TaxJob)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Create indicates an expected call of Create.
func (mr *MockTaxJobRepoMockRecorder) Create(ctx, job any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockTaxJobRepo)(nil).Create), ctx, job)
}

// Get mocks base method.
func (m *MockTaxJobRepo) Get(ctx context.Context, userID, jobID uuid.UUID) (domain.TaxJob, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Get", ctx, userID, jobID)
	ret0, _ := ret[0].(domain.TaxJob)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Get indicates an expected call of Get.
func (mr *MockTaxJobRepoMockRecorder) Get(ctx, userID, jobID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Get", reflect.TypeOf((*MockTaxJobRepo)(nil).Get), ctx, userID, jobID)
}

// List mocks base method.
func (m *MockTaxJobRepo) List(ctx context.Context, userID uuid.UUID, limit, offset int32) ([]domain.TaxJob, int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "List", ctx, userID, limit, offset)
	ret0, _ := ret[0].([]domain.TaxJob)
	ret1, _ := ret[1].(int64)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// List indicates an expected call of List.
func (mr *MockTaxJobRepoMockRecorder) List(ctx, userID, limit, offset any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "List", reflect.TypeOf((*MockTaxJobRepo)(nil).List), ctx, userID, limit, offset)
}

// MarkCanceled mocks base method.
func (m *MockTaxJobRepo) MarkCanceled(ctx context.Context, jobID uuid.UUID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "MarkCanceled", ctx, jobID)
	ret0, _ := ret[0].(error)
	return ret0
}

// MarkCanceled indicates an expected call of MarkCanceled.
func (mr *MockTaxJobRepoMockRecorder) MarkCanceled(ctx, jobID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "MarkCanceled", reflect.TypeOf((*MockTaxJobRepo)(nil).MarkCanceled), ctx, jobID)
}

// MarkFailed mocks base method.
func (m *MockTaxJobRepo) MarkFailed(ctx context.Context, jobID uuid.UUID, errCode, errMsg string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "MarkFailed", ctx, jobID, errCode, errMsg)
	ret0, _ := ret[0].(error)
	return ret0
}

// MarkFailed indicates an expected call of MarkFailed.
func (mr *MockTaxJobRepoMockRecorder) MarkFailed(ctx, jobID, errCode, errMsg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "MarkFailed", reflect.TypeOf((*MockTaxJobRepo)(nil).MarkFailed), ctx, jobID, errCode, errMsg)
}

// Requeue mocks base method.
func (m *MockTaxJobRepo) Requeue(ctx context.Context, jobID uuid.UUID, retryAt time.Time, errCode, errMsg string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Requeue", ctx, jobID, retryAt, errCode, errMsg)
	ret0, _ := ret[0].(error)
	return ret0
}

// Requeue indicates an expected call of Requeue.
func (mr *MockTaxJobRepoMockRecorder) Requeue(ctx, jobID, retryAt, errCode, errMsg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Requeue", reflect.TypeOf((*MockTaxJobRepo)(nil).Requeue), ctx, jobID, retryAt, errCode, errMsg)
}

// SaveResult mocks base method.
func (m *MockTaxJobRepo) SaveResult(ctx context.Context, jobID uuid.UUID, summary domain.TaxSummary, auditObjectKey, reportObjectKey *string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SaveResult", ctx, jobID, summary, auditObjectKey, reportObjectKey)
	ret0, _ := ret[0].(error)
	return ret0
}

// SaveResult indicates an expected call of SaveResult.
func (mr *MockTaxJobRepoMockRecorder) SaveResult(ctx, jobID, summary, auditObjectKey, reportObjectKey any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SaveResult", reflect.TypeOf((*MockTaxJobRepo)(nil).SaveResult), ctx, jobID, summary, auditObjectKey, reportObjectKey)
}

// MockObjectStorage is a mock of ObjectStorage interface.
type MockObjectStorage struct {
	ctrl     *gomock.Controller
	recorder *MockObjectStorageMockRecorder
	isgomock struct{}
}

// MockObjectStorageMockRecorder is the mock recorder for MockObjectStorage.
type MockObjectStorageMockRecorder struct {
	mock *MockObjectStorage
}

// NewMockObjectStorage creates a new mock instance.
func NewMockObjectStorage(ctrl *gomock.Controller) *MockObjectStorage {
	mock := &MockObjectStorage{ctrl: ctrl}
	mock.recorder = &MockObjectStorageMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockObjectStorage) EXPECT() *MockObjectStorageMockRecorder {
	return m.recorder
}

// PresignGet mocks base method.
func (m *MockObjectStorage) PresignGet(ctx context.Context, objectKey string) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "PresignGet", ctx, objectKey)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// PresignGet indicates an expected call of PresignGet.
func (mr *MockObjectStorageMockRecorder) PresignGet(ctx, objectKey any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "PresignGet", reflect.TypeOf((*MockObjectStorage)(nil).PresignGet), ctx, objectKey)
}

// UploadJSON mocks base method.
func (m *MockObjectStorage) UploadJSON(ctx context.Context, objectKey string, payload any) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UploadJSON", ctx, objectKey, payload)
	ret0, _ := ret[0].(error)
	return ret0
}

// UploadJSON indicates an expected call of UploadJSON.
func (mr *MockObjectStorageMockRecorder) UploadJSON(ctx, objectKey, payload any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UploadJSON", reflect.TypeOf((*MockObjectStorage)(nil).UploadJSON), ctx, objectKey, payload)
}

// MockAggregatedTxProvider is a mock of AggregatedTxProvider interface.
type MockAggregatedTxProvider struct {
	ctrl     *gomock.Controller
	recorder *MockAggregatedTxProviderMockRecorder
	isgomock struct{}
}

// MockAggregatedTxProviderMockRecorder is the mock recorder for MockAggregatedTxProvider.
type MockAggregatedTxProviderMockRecorder struct {
	mock *MockAggregatedTxProvider
}

// NewMockAggregatedTxProvider creates a new mock instance.
func NewMockAggregatedTxProvider(ctrl *gomock.Controller) *MockAggregatedTxProvider {
	mock := &MockAggregatedTxProvider{ctrl: ctrl}
	mock.recorder = &MockAggregatedTxProviderMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockAggregatedTxProvider) EXPECT() *MockAggregatedTxProviderMockRecorder {
	return m.recorder
}

// ListTransactionsByRange mocks base method.
func (m *MockAggregatedTxProvider) ListTransactionsByRange(ctx context.Context, userID uuid.UUID, fromUTC, toUTC time.Time, targetFiat string) ([]domain.AggregatedTransaction, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListTransactionsByRange", ctx, userID, fromUTC, toUTC, targetFiat)
	ret0, _ := ret[0].([]domain.AggregatedTransaction)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListTransactionsByRange indicates an expected call of ListTransactionsByRange.
func (mr *MockAggregatedTxProviderMockRecorder) ListTransactionsByRange(ctx, userID, fromUTC, toUTC, targetFiat any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListTransactionsByRange", reflect.TypeOf((*MockAggregatedTxProvider)(nil).ListTransactionsByRange), ctx, userID, fromUTC, toUTC, targetFiat)
}

// MockReportClient is a mock of ReportClient interface.
type MockReportClient struct {
	ctrl     *gomock.Controller
	recorder *MockReportClientMockRecorder
	isgomock struct{}
}

// MockReportClientMockRecorder is the mock recorder for MockReportClient.
type MockReportClientMockRecorder struct {
	mock *MockReportClient
}

// NewMockReportClient creates a new mock instance.
func NewMockReportClient(ctrl *gomock.Controller) *MockReportClient {
	mock := &MockReportClient{ctrl: ctrl}
	mock.recorder = &MockReportClientMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockReportClient) EXPECT() *MockReportClientMockRecorder {
	return m.recorder
}

// RequestRender mocks base method.
func (m *MockReportClient) RequestRender(ctx context.Context, req domain.ReportRenderRequest) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RequestRender", ctx, req)
	ret0, _ := ret[0].(error)
	return ret0
}

// RequestRender indicates an expected call of RequestRender.
func (mr *MockReportClientMockRecorder) RequestRender(ctx, req any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RequestRender", reflect.TypeOf((*MockReportClient)(nil).RequestRender), ctx, req)
}
