apiVersion: v1
kind: Service
metadata:
  name: tax-svc
spec:
  type: {{ .Values.service.type }}
  selector:
    app: tax-svc
  ports:
    - name: grpc
      port: {{ .Values.service.grpcPort }}
      targetPort: {{ .Values.service.grpcPort }}
    - name: http
      port: {{ .Values.service.httpPort }}
      targetPort: {{ .Values.service.httpPort }}
