// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: inbox_events.sql

package db

import (
	"context"

	"github.com/google/uuid"
)

const insertInboxEvent = `-- name: InsertInboxEvent :execrows
INSERT INTO inbox_events (event_id)
VALUES ($1)
ON CONFLICT (event_id) DO NOTHING
`

func (q *Queries) InsertInboxEvent(ctx context.Context, eventID uuid.UUID) (int64, error) {
	result, err := q.db.Exec(ctx, insertInboxEvent, eventID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
