// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type InboxEvent struct {
	EventID     uuid.UUID          `json:"eventId"`
	ProcessedAt pgtype.Timestamptz `json:"processedAt"`
}

type OutboxEvent struct {
	ID            uuid.UUID          `json:"id"`
	AggregateType string             `json:"aggregateType"`
	AggregateID   uuid.UUID          `json:"aggregateId"`
	EventType     string             `json:"eventType"`
	Payload       []byte             `json:"payload"`
	CreatedAt     pgtype.Timestamptz `json:"createdAt"`
	PublishedAt   pgtype.Timestamptz `json:"publishedAt"`
	Status        string             `json:"status"`
	Attempts      int32              `json:"attempts"`
	LastError     *string            `json:"lastError"`
}

type RenderJob struct {
	ReportID         uuid.UUID          `json:"reportId"`
	TenantID         uuid.UUID          `json:"tenantId"`
	Status           string             `json:"status"`
	StartedAt        pgtype.Timestamptz `json:"startedAt"`
	CompletedAt      pgtype.Timestamptz `json:"completedAt"`
	Error            *string            `json:"error"`
	DatasetObjectKey string             `json:"datasetObjectKey"`
	PdfObjectKey     *string            `json:"pdfObjectKey"`
	UpdatedAt        pgtype.Timestamptz `json:"updatedAt"`
}
