// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: outbox_events.sql

package db

import (
	"context"

	"github.com/google/uuid"
)

const insertOutboxEvent = `-- name: InsertOutboxEvent :exec
INSERT INTO outbox_events (
  id, aggregate_type, aggregate_id, event_type, payload, status
)
VALUES ($1, $2, $3, $4, $5, $6)
`

type InsertOutboxEventParams struct {
	ID            uuid.UUID `json:"id"`
	AggregateType string    `json:"aggregateType"`
	AggregateID   uuid.UUID `json:"aggregateId"`
	EventType     string    `json:"eventType"`
	Payload       []byte    `json:"payload"`
	Status        string    `json:"status"`
}

func (q *Queries) InsertOutboxEvent(ctx context.Context, arg InsertOutboxEventParams) error {
	_, err := q.db.Exec(ctx, insertOutboxEvent,
		arg.ID,
		arg.AggregateType,
		arg.AggregateID,
		arg.EventType,
		arg.Payload,
		arg.Status,
	)
	return err
}

const listPendingOutboxEvents = `-- name: ListPendingOutboxEvents :many
SELECT
  id, aggregate_type, aggregate_id, event_type, payload,
  created_at, published_at, status, attempts, last_error
FROM outbox_events
WHERE (status = 'pending' OR status = 'failed') AND attempts < $1
ORDER BY created_at ASC
LIMIT $2
`

type ListPendingOutboxEventsParams struct {
	Attempts int32 `json:"attempts"`
	Limit    int32 `json:"limit"`
}

func (q *Queries) ListPendingOutboxEvents(ctx context.Context, arg ListPendingOutboxEventsParams) ([]OutboxEvent, error) {
	rows, err := q.db.Query(ctx, listPendingOutboxEvents, arg.Attempts, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []OutboxEvent
	for rows.Next() {
		var i OutboxEvent
		if err := rows.Scan(
			&i.ID,
			&i.AggregateType,
			&i.AggregateID,
			&i.EventType,
			&i.Payload,
			&i.CreatedAt,
			&i.PublishedAt,
			&i.Status,
			&i.Attempts,
			&i.LastError,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markOutboxEventFailed = `-- name: MarkOutboxEventFailed :exec
UPDATE outbox_events
SET
  attempts = attempts + 1,
  last_error = $3,
  status = CASE WHEN attempts + 1 >= $2 THEN 'failed' ELSE 'pending' END
WHERE id = $1
`

type MarkOutboxEventFailedParams struct {
	ID        uuid.UUID `json:"id"`
	Attempts  int32     `json:"attempts"`
	LastError *string   `json:"lastError"`
}

func (q *Queries) MarkOutboxEventFailed(ctx context.Context, arg MarkOutboxEventFailedParams) error {
	_, err := q.db.Exec(ctx, markOutboxEventFailed, arg.ID, arg.Attempts, arg.LastError)
	return err
}

const markOutboxEventPublished = `-- name: MarkOutboxEventPublished :exec
UPDATE outbox_events
SET status = 'published', published_at = now(), attempts = attempts + 1, last_error = NULL
WHERE id = $1
`

func (q *Queries) MarkOutboxEventPublished(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, markOutboxEventPublished, id)
	return err
}
