// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"context"

	"github.com/google/uuid"
)

type Querier interface {
	InsertInboxEvent(ctx context.Context, eventID uuid.UUID) (int64, error)
	InsertOutboxEvent(ctx context.Context, arg InsertOutboxEventParams) error
	ListPendingOutboxEvents(ctx context.Context, arg ListPendingOutboxEventsParams) ([]OutboxEvent, error)
	MarkOutboxEventFailed(ctx context.Context, arg MarkOutboxEventFailedParams) error
	MarkOutboxEventPublished(ctx context.Context, id uuid.UUID) error
	MarkRenderJobCompleted(ctx context.Context, arg MarkRenderJobCompletedParams) error
	MarkRenderJobFailed(ctx context.Context, arg MarkRenderJobFailedParams) error
	UpsertRenderJobProcessing(ctx context.Context, arg UpsertRenderJobProcessingParams) error
}

var _ Querier = (*Queries)(nil)
