// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: render_jobs.sql

package db

import (
	"context"

	"github.com/google/uuid"
)

const markRenderJobCompleted = `-- name: MarkRenderJobCompleted :exec
UPDATE render_jobs
SET
  status = 'completed',
  completed_at = now(),
  error = NULL,
  pdf_object_key = $2,
  updated_at = now()
WHERE report_id = $1
`

type MarkRenderJobCompletedParams struct {
	ReportID     uuid.UUID `json:"reportId"`
	PdfObjectKey *string   `json:"pdfObjectKey"`
}

func (q *Queries) MarkRenderJobCompleted(ctx context.Context, arg MarkRenderJobCompletedParams) error {
	_, err := q.db.Exec(ctx, markRenderJobCompleted, arg.ReportID, arg.PdfObjectKey)
	return err
}

const markRenderJobFailed = `-- name: MarkRenderJobFailed :exec
UPDATE render_jobs
SET
  status = 'failed',
  completed_at = now(),
  error = $2,
  updated_at = now()
WHERE report_id = $1
`

type MarkRenderJobFailedParams struct {
	ReportID uuid.UUID `json:"reportId"`
	Error    *string   `json:"error"`
}

func (q *Queries) MarkRenderJobFailed(ctx context.Context, arg MarkRenderJobFailedParams) error {
	_, err := q.db.Exec(ctx, markRenderJobFailed, arg.ReportID, arg.Error)
	return err
}

const upsertRenderJobProcessing = `-- name: UpsertRenderJobProcessing :exec
INSERT INTO render_jobs (
  report_id, tenant_id, status, dataset_object_key, started_at, updated_at
)
VALUES ($1, $2, 'processing', $3, now(), now())
ON CONFLICT (report_id) DO UPDATE
SET
  tenant_id = EXCLUDED.tenant_id,
  status = 'processing',
  completed_at = NULL,
  error = NULL,
  dataset_object_key = EXCLUDED.dataset_object_key,
  updated_at = now()
`

type UpsertRenderJobProcessingParams struct {
	ReportID         uuid.UUID `json:"reportId"`
	TenantID         uuid.UUID `json:"tenantId"`
	DatasetObjectKey string    `json:"datasetObjectKey"`
}

func (q *Queries) UpsertRenderJobProcessing(ctx context.Context, arg UpsertRenderJobProcessingParams) error {
	_, err := q.db.Exec(ctx, upsertRenderJobProcessing, arg.ReportID, arg.TenantID, arg.DatasetObjectKey)
	return err
}
