// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: aggregated_transactions.sql

package db

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const countAggregatedTransactionsByImport = `-- name: CountAggregatedTransactionsByImport :one
SELECT count(*)
FROM aggregated_transactions
WHERE tenant_id = $1 AND import_id = $2
`

type CountAggregatedTransactionsByImportParams struct {
	TenantID uuid.UUID `json:"tenantId"`
	ImportID uuid.UUID `json:"importId"`
}

func (q *Queries) CountAggregatedTransactionsByImport(ctx context.Context, arg CountAggregatedTransactionsByImportParams) (int64, error) {
	row := q.db.QueryRow(ctx, countAggregatedTransactionsByImport, arg.TenantID, arg.ImportID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const listAggregatedTransactionsByImport = `-- name: ListAggregatedTransactionsByImport :many
SELECT
  id,
  tenant_id,
  wallet,
  source,
  import_id,
  time_utc,
  kind,
  in_money,
  out_money,
  fee_money,
  contract_symbol,
  derivative_kind,
  position_id,
  order_id,
  tx_hash,
  note,
  tx_fingerprint,
  created_at,
  updated_at
FROM aggregated_transactions
WHERE tenant_id = $1 AND import_id = $2
ORDER BY time_utc DESC
LIMIT $3 OFFSET $4
`

type ListAggregatedTransactionsByImportParams struct {
	TenantID uuid.UUID `json:"tenantId"`
	ImportID uuid.UUID `json:"importId"`
	Limit    int32     `json:"limit"`
	Offset   int32     `json:"offset"`
}

func (q *Queries) ListAggregatedTransactionsByImport(ctx context.Context, arg ListAggregatedTransactionsByImportParams) ([]AggregatedTransaction, error) {
	rows, err := q.db.Query(ctx, listAggregatedTransactionsByImport,
		arg.TenantID,
		arg.ImportID,
		arg.Limit,
		arg.Offset,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []AggregatedTransaction
	for rows.Next() {
		var i AggregatedTransaction
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.Wallet,
			&i.Source,
			&i.ImportID,
			&i.TimeUtc,
			&i.Kind,
			&i.InMoney,
			&i.OutMoney,
			&i.FeeMoney,
			&i.ContractSymbol,
			&i.DerivativeKind,
			&i.PositionID,
			&i.OrderID,
			&i.TxHash,
			&i.Note,
			&i.TxFingerprint,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertAggregatedTransaction = `-- name: UpsertAggregatedTransaction :exec
INSERT INTO aggregated_transactions (
  id,
  tenant_id,
  wallet,
  source,
  import_id,
  time_utc,
  kind,
  in_money,
  out_money,
  fee_money,
  contract_symbol,
  derivative_kind,
  position_id,
  order_id,
  tx_hash,
  note,
  tx_fingerprint,
  created_at
)
VALUES (
  $1, $2, $3, $4, $5, $6, $7,
  $8, $9, $10,
  $11, $12, $13, $14, $15, $16,
  $17, $18
)
ON CONFLICT (id)
DO UPDATE SET
  wallet = EXCLUDED.wallet,
  source = EXCLUDED.source,
  import_id = EXCLUDED.import_id,
  time_utc = EXCLUDED.time_utc,
  kind = EXCLUDED.kind,
  in_money = EXCLUDED.in_money,
  out_money = EXCLUDED.out_money,
  fee_money = EXCLUDED.fee_money,
  contract_symbol = EXCLUDED.contract_symbol,
  derivative_kind = EXCLUDED.derivative_kind,
  position_id = EXCLUDED.position_id,
  order_id = EXCLUDED.order_id,
  tx_hash = EXCLUDED.tx_hash,
  note = EXCLUDED.note,
  tx_fingerprint = EXCLUDED.tx_fingerprint,
  updated_at = now()
`

type UpsertAggregatedTransactionParams struct {
	ID             uuid.UUID          `json:"id"`
	TenantID       uuid.UUID          `json:"tenantId"`
	Wallet         string             `json:"wallet"`
	Source         string             `json:"source"`
	ImportID       uuid.UUID          `json:"importId"`
	TimeUtc        pgtype.Timestamptz `json:"timeUtc"`
	Kind           string             `json:"kind"`
	InMoney        []byte             `json:"inMoney"`
	OutMoney       []byte             `json:"outMoney"`
	FeeMoney       []byte             `json:"feeMoney"`
	ContractSymbol *string            `json:"contractSymbol"`
	DerivativeKind *string            `json:"derivativeKind"`
	PositionID     *string            `json:"positionId"`
	OrderID        *string            `json:"orderId"`
	TxHash         *string            `json:"txHash"`
	Note           *string            `json:"note"`
	TxFingerprint  string             `json:"txFingerprint"`
	CreatedAt      pgtype.Timestamptz `json:"createdAt"`
}

func (q *Queries) UpsertAggregatedTransaction(ctx context.Context, arg UpsertAggregatedTransactionParams) error {
	_, err := q.db.Exec(ctx, upsertAggregatedTransaction,
		arg.ID,
		arg.TenantID,
		arg.Wallet,
		arg.Source,
		arg.ImportID,
		arg.TimeUtc,
		arg.Kind,
		arg.InMoney,
		arg.OutMoney,
		arg.FeeMoney,
		arg.ContractSymbol,
		arg.DerivativeKind,
		arg.PositionID,
		arg.OrderID,
		arg.TxHash,
		arg.Note,
		arg.TxFingerprint,
		arg.CreatedAt,
	)
	return err
}
