// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type AggregatedTransaction struct {
	ID             uuid.UUID          `json:"id"`
	UserID         uuid.UUID          `json:"userId"`
	Source         string             `json:"source"`
	ImportID       uuid.UUID          `json:"importId"`
	TimeUtc        pgtype.Timestamptz `json:"timeUtc"`
	Kind           string             `json:"kind"`
	InMoney        []byte             `json:"inMoney"`
	OutMoney       []byte             `json:"outMoney"`
	FeeMoney       []byte             `json:"feeMoney"`
	ContractSymbol *string            `json:"contractSymbol"`
	DerivativeKind *string            `json:"derivativeKind"`
	PositionID     *string            `json:"positionId"`
	OrderID        *string            `json:"orderId"`
	TxHash         *string            `json:"txHash"`
	Note           *string            `json:"note"`
	TxFingerprint  string             `json:"txFingerprint"`
	CreatedAt      pgtype.Timestamptz `json:"createdAt"`
	UpdatedAt      pgtype.Timestamptz `json:"updatedAt"`
}

type AggregationImportState struct {
	UserID      uuid.UUID          `json:"userId"`
	ImportID    uuid.UUID          `json:"importId"`
	EventID     uuid.UUID          `json:"eventId"`
	Status      string             `json:"status"`
	StartedAt   pgtype.Timestamptz `json:"startedAt"`
	CompletedAt pgtype.Timestamptz `json:"completedAt"`
	Error       *string            `json:"error"`
}

type UserSetting struct {
	UserID       uuid.UUID          `json:"userId"`
	FiatCurrency string             `json:"fiatCurrency"`
	Timezone     string             `json:"timezone"`
	UpdatedAt    pgtype.Timestamptz `json:"updatedAt"`
}
