// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"context"

	"github.com/google/uuid"
)

type Querier interface {
	CountAggregatedTransactionsByImport(ctx context.Context, arg CountAggregatedTransactionsByImportParams) (int64, error)
	GetAggregationImportState(ctx context.Context, arg GetAggregationImportStateParams) (AggregationImportState, error)
	GetTenantSettings(ctx context.Context, tenantID uuid.UUID) (TenantSetting, error)
	ListAggregatedTransactionsByImport(ctx context.Context, arg ListAggregatedTransactionsByImportParams) ([]AggregatedTransaction, error)
	MarkAggregationImportStateCompleted(ctx context.Context, arg MarkAggregationImportStateCompletedParams) error
	MarkAggregationImportStateFailed(ctx context.Context, arg MarkAggregationImportStateFailedParams) error
	UpsertAggregatedTransaction(ctx context.Context, arg UpsertAggregatedTransactionParams) error
	UpsertAggregationImportStateProcessing(ctx context.Context, arg UpsertAggregationImportStateProcessingParams) error
	UpsertTenantSettings(ctx context.Context, arg UpsertTenantSettingsParams) (TenantSetting, error)
}

var _ Querier = (*Queries)(nil)
