// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"context"

	"github.com/google/uuid"
)

type Querier interface {
	CountAggregatedTransactionsByRange(ctx context.Context, arg CountAggregatedTransactionsByRangeParams) (int64, error)
	GetAggregationImportState(ctx context.Context, arg GetAggregationImportStateParams) (AggregationImportState, error)
	GetUserSettings(ctx context.Context, userID uuid.UUID) (UserSetting, error)
	ListAggregatedTransactions(ctx context.Context, arg ListAggregatedTransactionsParams) ([]AggregatedTransaction, error)
	ListAggregatedTransactionsByRange(ctx context.Context, arg ListAggregatedTransactionsByRangeParams) ([]AggregatedTransaction, error)
	MarkAggregationImportStateCompleted(ctx context.Context, arg MarkAggregationImportStateCompletedParams) error
	MarkAggregationImportStateFailed(ctx context.Context, arg MarkAggregationImportStateFailedParams) error
	UpdateAggregatedTransactionByFingerprint(ctx context.Context, arg UpdateAggregatedTransactionByFingerprintParams) (int64, error)
	UpsertAggregatedTransaction(ctx context.Context, arg UpsertAggregatedTransactionParams) error
	UpsertAggregationImportStateProcessing(ctx context.Context, arg UpsertAggregationImportStateProcessingParams) error
	UpsertUserSettings(ctx context.Context, arg UpsertUserSettingsParams) (UserSetting, error)
}

var _ Querier = (*Queries)(nil)
