// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: tenant_settings.sql

package db

import (
	"context"

	"github.com/google/uuid"
)

const getTenantSettings = `-- name: GetTenantSettings :one
SELECT tenant_id, fiat_currency, timezone, updated_at
FROM tenant_settings
WHERE tenant_id = $1
`

func (q *Queries) GetTenantSettings(ctx context.Context, tenantID uuid.UUID) (TenantSetting, error) {
	row := q.db.QueryRow(ctx, getTenantSettings, tenantID)
	var i TenantSetting
	err := row.Scan(
		&i.TenantID,
		&i.FiatCurrency,
		&i.Timezone,
		&i.UpdatedAt,
	)
	return i, err
}

const upsertTenantSettings = `-- name: UpsertTenantSettings :one
INSERT INTO tenant_settings (tenant_id, fiat_currency, timezone)
VALUES ($1, $2, $3)
ON CONFLICT (tenant_id)
DO UPDATE SET
  fiat_currency = EXCLUDED.fiat_currency,
  timezone = EXCLUDED.timezone,
  updated_at = now()
RETURNING tenant_id, fiat_currency, timezone, updated_at
`

type UpsertTenantSettingsParams struct {
	TenantID     uuid.UUID `json:"tenantId"`
	FiatCurrency string    `json:"fiatCurrency"`
	Timezone     string    `json:"timezone"`
}

func (q *Queries) UpsertTenantSettings(ctx context.Context, arg UpsertTenantSettingsParams) (TenantSetting, error) {
	row := q.db.QueryRow(ctx, upsertTenantSettings, arg.TenantID, arg.FiatCurrency, arg.Timezone)
	var i TenantSetting
	err := row.Scan(
		&i.TenantID,
		&i.FiatCurrency,
		&i.Timezone,
		&i.UpdatedAt,
	)
	return i, err
}
