// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: user_settings.sql

package db

import (
	"context"

	"github.com/google/uuid"
)

const getUserSettings = `-- name: GetUserSettings :one
SELECT user_id, fiat_currency, timezone, updated_at
FROM user_settings
WHERE user_id = $1
`

func (q *Queries) GetUserSettings(ctx context.Context, userID uuid.UUID) (UserSetting, error) {
	row := q.db.QueryRow(ctx, getUserSettings, userID)
	var i UserSetting
	err := row.Scan(
		&i.UserID,
		&i.FiatCurrency,
		&i.Timezone,
		&i.UpdatedAt,
	)
	return i, err
}

const upsertUserSettings = `-- name: UpsertUserSettings :one
INSERT INTO user_settings (user_id, fiat_currency, timezone)
VALUES ($1, $2, $3)
ON CONFLICT (user_id)
DO UPDATE SET
  fiat_currency = EXCLUDED.fiat_currency,
  timezone = EXCLUDED.timezone,
  updated_at = now()
RETURNING user_id, fiat_currency, timezone, updated_at
`

type UpsertUserSettingsParams struct {
	UserID       uuid.UUID `json:"userId"`
	FiatCurrency string    `json:"fiatCurrency"`
	Timezone     string    `json:"timezone"`
}

func (q *Queries) UpsertUserSettings(ctx context.Context, arg UpsertUserSettingsParams) (UserSetting, error) {
	row := q.db.QueryRow(ctx, upsertUserSettings, arg.UserID, arg.FiatCurrency, arg.Timezone)
	var i UserSetting
	err := row.Scan(
		&i.UserID,
		&i.FiatCurrency,
		&i.Timezone,
		&i.UpdatedAt,
	)
	return i, err
}
