// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/NightRunner/CryptoTax-Go/services/aggregation-svc/internal/domain (interfaces: AggregationUseCase,TenantSettingsUseCase)
//
// Generated by this command:
//
//	mockgen -destination=server_uc_mocks.gen.go -package=mocks github.com/NightRunner/CryptoTax-Go/services/aggregation-svc/internal/domain AggregationUseCase,TenantSettingsUseCase
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"
	time "time"

	domain "github.com/NightRunner/CryptoTax-Go/services/aggregation-svc/internal/domain"
	uuid "github.com/google/uuid"
	gomock "go.uber.org/mock/gomock"
)

// MockAggregationUseCase is a mock of AggregationUseCase interface.
type MockAggregationUseCase struct {
	ctrl     *gomock.Controller
	recorder *MockAggregationUseCaseMockRecorder
	isgomock struct{}
}

// MockAggregationUseCaseMockRecorder is the mock recorder for MockAggregationUseCase.
type MockAggregationUseCaseMockRecorder struct {
	mock *MockAggregationUseCase
}

// NewMockAggregationUseCase creates a new mock instance.
func NewMockAggregationUseCase(ctrl *gomock.Controller) *MockAggregationUseCase {
	mock := &MockAggregationUseCase{ctrl: ctrl}
	mock.recorder = &MockAggregationUseCaseMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockAggregationUseCase) EXPECT() *MockAggregationUseCaseMockRecorder {
	return m.recorder
}

// ListTransactionsByImport mocks base method.
func (m *MockAggregationUseCase) ListTransactionsByImport(ctx context.Context, tenantID, importID uuid.UUID, limit, offset int32) (domain.AggregatedTxPage, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListTransactionsByImport", ctx, tenantID, importID, limit, offset)
	ret0, _ := ret[0].(domain.AggregatedTxPage)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListTransactionsByImport indicates an expected call of ListTransactionsByImport.
func (mr *MockAggregationUseCaseMockRecorder) ListTransactionsByImport(ctx, tenantID, importID, limit, offset any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListTransactionsByImport", reflect.TypeOf((*MockAggregationUseCase)(nil).ListTransactionsByImport), ctx, tenantID, importID, limit, offset)
}

// ListTransactionsByRange mocks base method.
func (m *MockAggregationUseCase) ListTransactionsByRange(ctx context.Context, tenantID uuid.UUID, fromUTC, toUTC time.Time, limit, offset int32, targetFiat string) (domain.AggregatedTxPage, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListTransactionsByRange", ctx, tenantID, fromUTC, toUTC, limit, offset, targetFiat)
	ret0, _ := ret[0].(domain.AggregatedTxPage)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListTransactionsByRange indicates an expected call of ListTransactionsByRange.
func (mr *MockAggregationUseCaseMockRecorder) ListTransactionsByRange(ctx, tenantID, fromUTC, toUTC, limit, offset, targetFiat any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListTransactionsByRange", reflect.TypeOf((*MockAggregationUseCase)(nil).ListTransactionsByRange), ctx, tenantID, fromUTC, toUTC, limit, offset, targetFiat)
}

// ProcessImport mocks base method.
func (m *MockAggregationUseCase) ProcessImport(ctx context.Context, event domain.ImportEvent) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ProcessImport", ctx, event)
	ret0, _ := ret[0].(error)
	return ret0
}

// ProcessImport indicates an expected call of ProcessImport.
func (mr *MockAggregationUseCaseMockRecorder) ProcessImport(ctx, event any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ProcessImport", reflect.TypeOf((*MockAggregationUseCase)(nil).ProcessImport), ctx, event)
}

// MockTenantSettingsUseCase is a mock of TenantSettingsUseCase interface.
type MockTenantSettingsUseCase struct {
	ctrl     *gomock.Controller
	recorder *MockTenantSettingsUseCaseMockRecorder
	isgomock struct{}
}

// MockTenantSettingsUseCaseMockRecorder is the mock recorder for MockTenantSettingsUseCase.
type MockTenantSettingsUseCaseMockRecorder struct {
	mock *MockTenantSettingsUseCase
}

// NewMockTenantSettingsUseCase creates a new mock instance.
func NewMockTenantSettingsUseCase(ctrl *gomock.Controller) *MockTenantSettingsUseCase {
	mock := &MockTenantSettingsUseCase{ctrl: ctrl}
	mock.recorder = &MockTenantSettingsUseCaseMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockTenantSettingsUseCase) EXPECT() *MockTenantSettingsUseCaseMockRecorder {
	return m.recorder
}

// Get mocks base method.
func (m *MockTenantSettingsUseCase) Get(ctx context.Context, tenantID uuid.UUID) (domain.TenantSettings, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Get", ctx, tenantID)
	ret0, _ := ret[0].(domain.TenantSettings)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Get indicates an expected call of Get.
func (mr *MockTenantSettingsUseCaseMockRecorder) Get(ctx, tenantID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Get", reflect.TypeOf((*MockTenantSettingsUseCase)(nil).Get), ctx, tenantID)
}

// ListSupportedFiatCurrencies mocks base method.
func (m *MockTenantSettingsUseCase) ListSupportedFiatCurrencies(ctx context.Context) ([]domain.SupportedFiatCurrency, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListSupportedFiatCurrencies", ctx)
	ret0, _ := ret[0].([]domain.SupportedFiatCurrency)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListSupportedFiatCurrencies indicates an expected call of ListSupportedFiatCurrencies.
func (mr *MockTenantSettingsUseCaseMockRecorder) ListSupportedFiatCurrencies(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListSupportedFiatCurrencies", reflect.TypeOf((*MockTenantSettingsUseCase)(nil).ListSupportedFiatCurrencies), ctx)
}

// Upsert mocks base method.
func (m *MockTenantSettingsUseCase) Upsert(ctx context.Context, settings domain.TenantSettings) (domain.TenantSettings, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Upsert", ctx, settings)
	ret0, _ := ret[0].(domain.TenantSettings)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Upsert indicates an expected call of Upsert.
func (mr *MockTenantSettingsUseCaseMockRecorder) Upsert(ctx, settings any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Upsert", reflect.TypeOf((*MockTenantSettingsUseCase)(nil).Upsert), ctx, settings)
}
