// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/NightRunner/CryptoTax-Go/services/aggregation-svc/internal/domain (interfaces: AggregatedTransactionRepo,ImportStateRepo,UserSettingsRepo,LedgerClient,PriceClient,LockManager)
//
// Generated by this command:
//
//	mockgen -destination=usecase_deps_mocks.gen.go -package=mocks github.com/NightRunner/CryptoTax-Go/services/aggregation-svc/internal/domain AggregatedTransactionRepo,ImportStateRepo,UserSettingsRepo,LedgerClient,PriceClient,LockManager
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"
	time "time"

	pricev1 "github.com/NightRunner/CryptoTax-Go/gen/price/v1"
	domain "github.com/NightRunner/CryptoTax-Go/services/aggregation-svc/internal/domain"
	uuid "github.com/google/uuid"
	gomock "go.uber.org/mock/gomock"
)

// MockAggregatedTransactionRepo is a mock of AggregatedTransactionRepo interface.
type MockAggregatedTransactionRepo struct {
	ctrl     *gomock.Controller
	recorder *MockAggregatedTransactionRepoMockRecorder
	isgomock struct{}
}

// MockAggregatedTransactionRepoMockRecorder is the mock recorder for MockAggregatedTransactionRepo.
type MockAggregatedTransactionRepoMockRecorder struct {
	mock *MockAggregatedTransactionRepo
}

// NewMockAggregatedTransactionRepo creates a new mock instance.
func NewMockAggregatedTransactionRepo(ctrl *gomock.Controller) *MockAggregatedTransactionRepo {
	mock := &MockAggregatedTransactionRepo{ctrl: ctrl}
	mock.recorder = &MockAggregatedTransactionRepoMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockAggregatedTransactionRepo) EXPECT() *MockAggregatedTransactionRepoMockRecorder {
	return m.recorder
}

// List mocks base method.
func (m *MockAggregatedTransactionRepo) List(ctx context.Context, userID uuid.UUID, filter domain.ListTransactionsFilter, pageSize int32, cursor *domain.AggregatedTxCursor) ([]domain.AggregatedTransaction, bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "List", ctx, userID, filter, pageSize, cursor)
	ret0, _ := ret[0].([]domain.AggregatedTransaction)
	ret1, _ := ret[1].(bool)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// List indicates an expected call of List.
func (mr *MockAggregatedTransactionRepoMockRecorder) List(ctx, userID, filter, pageSize, cursor any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "List", reflect.TypeOf((*MockAggregatedTransactionRepo)(nil).List), ctx, userID, filter, pageSize, cursor)
}

// ListByRange mocks base method.
func (m *MockAggregatedTransactionRepo) ListByRange(ctx context.Context, userID uuid.UUID, fromUTC, toUTC time.Time, limit, offset int32) (domain.AggregatedTxPage, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListByRange", ctx, userID, fromUTC, toUTC, limit, offset)
	ret0, _ := ret[0].(domain.AggregatedTxPage)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListByRange indicates an expected call of ListByRange.
func (mr *MockAggregatedTransactionRepoMockRecorder) ListByRange(ctx, userID, fromUTC, toUTC, limit, offset any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListByRange", reflect.TypeOf((*MockAggregatedTransactionRepo)(nil).ListByRange), ctx, userID, fromUTC, toUTC, limit, offset)
}

// UpsertBatch mocks base method.
func (m *MockAggregatedTransactionRepo) UpsertBatch(ctx context.Context, txs []domain.AggregatedTransaction) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpsertBatch", ctx, txs)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpsertBatch indicates an expected call of UpsertBatch.
func (mr *MockAggregatedTransactionRepoMockRecorder) UpsertBatch(ctx, txs any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpsertBatch", reflect.TypeOf((*MockAggregatedTransactionRepo)(nil).UpsertBatch), ctx, txs)
}

// MockImportStateRepo is a mock of ImportStateRepo interface.
type MockImportStateRepo struct {
	ctrl     *gomock.Controller
	recorder *MockImportStateRepoMockRecorder
	isgomock struct{}
}

// MockImportStateRepoMockRecorder is the mock recorder for MockImportStateRepo.
type MockImportStateRepoMockRecorder struct {
	mock *MockImportStateRepo
}

// NewMockImportStateRepo creates a new mock instance.
func NewMockImportStateRepo(ctrl *gomock.Controller) *MockImportStateRepo {
	mock := &MockImportStateRepo{ctrl: ctrl}
	mock.recorder = &MockImportStateRepoMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockImportStateRepo) EXPECT() *MockImportStateRepoMockRecorder {
	return m.recorder
}

// Get mocks base method.
func (m *MockImportStateRepo) Get(ctx context.Context, userID, importID uuid.UUID) (domain.AggregationImportState, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Get", ctx, userID, importID)
	ret0, _ := ret[0].(domain.AggregationImportState)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Get indicates an expected call of Get.
func (mr *MockImportStateRepoMockRecorder) Get(ctx, userID, importID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Get", reflect.TypeOf((*MockImportStateRepo)(nil).Get), ctx, userID, importID)
}

// MarkCompleted mocks base method.
func (m *MockImportStateRepo) MarkCompleted(ctx context.Context, userID, importID uuid.UUID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "MarkCompleted", ctx, userID, importID)
	ret0, _ := ret[0].(error)
	return ret0
}

// MarkCompleted indicates an expected call of MarkCompleted.
func (mr *MockImportStateRepoMockRecorder) MarkCompleted(ctx, userID, importID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "MarkCompleted", reflect.TypeOf((*MockImportStateRepo)(nil).MarkCompleted), ctx, userID, importID)
}

// MarkFailed mocks base method.
func (m *MockImportStateRepo) MarkFailed(ctx context.Context, userID, importID uuid.UUID, errMsg string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "MarkFailed", ctx, userID, importID, errMsg)
	ret0, _ := ret[0].(error)
	return ret0
}

// MarkFailed indicates an expected call of MarkFailed.
func (mr *MockImportStateRepoMockRecorder) MarkFailed(ctx, userID, importID, errMsg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "MarkFailed", reflect.TypeOf((*MockImportStateRepo)(nil).MarkFailed), ctx, userID, importID, errMsg)
}

// UpsertProcessing mocks base method.
func (m *MockImportStateRepo) UpsertProcessing(ctx context.Context, state domain.AggregationImportState) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpsertProcessing", ctx, state)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpsertProcessing indicates an expected call of UpsertProcessing.
func (mr *MockImportStateRepoMockRecorder) UpsertProcessing(ctx, state any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpsertProcessing", reflect.TypeOf((*MockImportStateRepo)(nil).UpsertProcessing), ctx, state)
}

// MockUserSettingsRepo is a mock of UserSettingsRepo interface.
type MockUserSettingsRepo struct {
	ctrl     *gomock.Controller
	recorder *MockUserSettingsRepoMockRecorder
	isgomock struct{}
}

// MockUserSettingsRepoMockRecorder is the mock recorder for MockUserSettingsRepo.
type MockUserSettingsRepoMockRecorder struct {
	mock *MockUserSettingsRepo
}

// NewMockUserSettingsRepo creates a new mock instance.
func NewMockUserSettingsRepo(ctrl *gomock.Controller) *MockUserSettingsRepo {
	mock := &MockUserSettingsRepo{ctrl: ctrl}
	mock.recorder = &MockUserSettingsRepoMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockUserSettingsRepo) EXPECT() *MockUserSettingsRepoMockRecorder {
	return m.recorder
}

// Get mocks base method.
func (m *MockUserSettingsRepo) Get(ctx context.Context, userID uuid.UUID) (domain.UserSettings, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Get", ctx, userID)
	ret0, _ := ret[0].(domain.UserSettings)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Get indicates an expected call of Get.
func (mr *MockUserSettingsRepoMockRecorder) Get(ctx, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Get", reflect.TypeOf((*MockUserSettingsRepo)(nil).Get), ctx, userID)
}

// Upsert mocks base method.
func (m *MockUserSettingsRepo) Upsert(ctx context.Context, settings domain.UserSettings) (domain.UserSettings, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Upsert", ctx, settings)
	ret0, _ := ret[0].(domain.UserSettings)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Upsert indicates an expected call of Upsert.
func (mr *MockUserSettingsRepoMockRecorder) Upsert(ctx, settings any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Upsert", reflect.TypeOf((*MockUserSettingsRepo)(nil).Upsert), ctx, settings)
}

// MockLedgerClient is a mock of LedgerClient interface.
type MockLedgerClient struct {
	ctrl     *gomock.Controller
	recorder *MockLedgerClientMockRecorder
	isgomock struct{}
}

// MockLedgerClientMockRecorder is the mock recorder for MockLedgerClient.
type MockLedgerClientMockRecorder struct {
	mock *MockLedgerClient
}

// NewMockLedgerClient creates a new mock instance.
func NewMockLedgerClient(ctrl *gomock.Controller) *MockLedgerClient {
	mock := &MockLedgerClient{ctrl: ctrl}
	mock.recorder = &MockLedgerClientMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockLedgerClient) EXPECT() *MockLedgerClientMockRecorder {
	return m.recorder
}

// ListTransactionsByImport mocks base method.
func (m *MockLedgerClient) ListTransactionsByImport(ctx context.Context, userID, importID uuid.UUID) ([]domain.LedgerTransaction, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListTransactionsByImport", ctx, userID, importID)
	ret0, _ := ret[0].([]domain.LedgerTransaction)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListTransactionsByImport indicates an expected call of ListTransactionsByImport.
func (mr *MockLedgerClientMockRecorder) ListTransactionsByImport(ctx, userID, importID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListTransactionsByImport", reflect.TypeOf((*MockLedgerClient)(nil).ListTransactionsByImport), ctx, userID, importID)
}

// MockPriceClient is a mock of PriceClient interface.
type MockPriceClient struct {
	ctrl     *gomock.Controller
	recorder *MockPriceClientMockRecorder
	isgomock struct{}
}

// MockPriceClientMockRecorder is the mock recorder for MockPriceClient.
type MockPriceClientMockRecorder struct {
	mock *MockPriceClient
}

// NewMockPriceClient creates a new mock instance.
func NewMockPriceClient(ctrl *gomock.Controller) *MockPriceClient {
	mock := &MockPriceClient{ctrl: ctrl}
	mock.recorder = &MockPriceClientMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockPriceClient) EXPECT() *MockPriceClientMockRecorder {
	return m.recorder
}

// ValuateTransactionsBatch mocks base method.
func (m *MockPriceClient) ValuateTransactionsBatch(ctx context.Context, req *pricev1.ValuateTransactionsRequest) (*pricev1.ValuateTransactionsResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ValuateTransactionsBatch", ctx, req)
	ret0, _ := ret[0].(*pricev1.ValuateTransactionsResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ValuateTransactionsBatch indicates an expected call of ValuateTransactionsBatch.
func (mr *MockPriceClientMockRecorder) ValuateTransactionsBatch(ctx, req any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ValuateTransactionsBatch", reflect.TypeOf((*MockPriceClient)(nil).ValuateTransactionsBatch), ctx, req)
}

// MockLockManager is a mock of LockManager interface.
type MockLockManager struct {
	ctrl     *gomock.Controller
	recorder *MockLockManagerMockRecorder
	isgomock struct{}
}

// MockLockManagerMockRecorder is the mock recorder for MockLockManager.
type MockLockManagerMockRecorder struct {
	mock *MockLockManager
}

// NewMockLockManager creates a new mock instance.
func NewMockLockManager(ctrl *gomock.Controller) *MockLockManager {
	mock := &MockLockManager{ctrl: ctrl}
	mock.recorder = &MockLockManagerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockLockManager) EXPECT() *MockLockManagerMockRecorder {
	return m.recorder
}

// AcquireImportLock mocks base method.
func (m *MockLockManager) AcquireImportLock(ctx context.Context, userID, importID uuid.UUID, ttl time.Duration) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AcquireImportLock", ctx, userID, importID, ttl)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// AcquireImportLock indicates an expected call of AcquireImportLock.
func (mr *MockLockManagerMockRecorder) AcquireImportLock(ctx, userID, importID, ttl any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AcquireImportLock", reflect.TypeOf((*MockLockManager)(nil).AcquireImportLock), ctx, userID, importID, ttl)
}

// ReleaseImportLock mocks base method.
func (m *MockLockManager) ReleaseImportLock(ctx context.Context, userID, importID uuid.UUID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ReleaseImportLock", ctx, userID, importID)
	ret0, _ := ret[0].(error)
	return ret0
}

// ReleaseImportLock indicates an expected call of ReleaseImportLock.
func (mr *MockLockManagerMockRecorder) ReleaseImportLock(ctx, userID, importID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ReleaseImportLock", reflect.TypeOf((*MockLockManager)(nil).ReleaseImportLock), ctx, userID, importID)
}
