apiVersion: networking.istio.io/v1
kind: Gateway
metadata:
  name: cryptotax-gateway
  namespace: cryptotax
spec:
  selector:
    istio: ingressgateway
  servers:
    - port:
        number: 80
        name: http
        protocol: HTTP
      hosts:
        - "localhost" # for testing only, change to your domain in production
        - "127.0.0.1"
