#!/usr/bin/env bash
set -euo pipefail

SECRETS_FILE="${1:-deploy/local-secrets/vault.local.env}"
VAULT_CONTAINER="${VAULT_CONTAINER:-vault}"
VAULT_ADDR="${VAULT_ADDR:-http://127.0.0.1:8200}"
VAULT_TOKEN="${VAULT_TOKEN:-root}"
VAULT_MOUNT="${VAULT_MOUNT:-secret}"

if [[ ! -f "$SECRETS_FILE" ]]; then
  echo "secrets file not found: $SECRETS_FILE" >&2
  exit 1
fi

if ! docker ps --format '{{.Names}}' | grep -qx "$VAULT_CONTAINER"; then
  echo "vault container '$VAULT_CONTAINER' is not running" >&2
  exit 1
fi

set -a
# shellcheck disable=SC1090
source "$SECRETS_FILE"
set +a

vault_kv_put() {
  local path="$1"
  shift
  docker exec \
    -e VAULT_ADDR="$VAULT_ADDR" \
    -e VAULT_TOKEN="$VAULT_TOKEN" \
    "$VAULT_CONTAINER" \
    vault kv put -mount="$VAULT_MOUNT" "$path" "$@"
}

echo "seeding local vault from: $SECRETS_FILE"

vault_kv_put cryptotax/price-svc \
  APP_VERSION="$APP_VERSION" \
  APP_ENV="$APP_ENV" \
  DATABASE_URL="$PRICE_DATABASE_URL" \
  REDIS_URL="$REDIS_URL" \
  COINGECKO_API_KEY="$COINGECKO_API_KEY" \
  OTEL_EXPORTER_OTLP_ENDPOINT="$OTEL_EXPORTER_OTLP_ENDPOINT" \
  OTEL_EXPORTER_OTLP_INSECURE="$OTEL_EXPORTER_OTLP_INSECURE"

vault_kv_put cryptotax/aggregation-svc \
  APP_VERSION="$APP_VERSION" \
  APP_ENV="$APP_ENV" \
  DATABASE_URL="$AGGREGATION_DATABASE_URL" \
  REDIS_URL="$REDIS_URL" \
  LEDGER_SVC_BASE_URL="$LEDGER_SVC_BASE_URL" \
  PRICE_SVC_ADDR="$PRICE_SVC_ADDR" \
  RABBITMQ_URL="$RABBITMQ_URL" \
  OTEL_EXPORTER_OTLP_ENDPOINT="$OTEL_EXPORTER_OTLP_ENDPOINT" \
  OTEL_EXPORTER_OTLP_INSECURE="$OTEL_EXPORTER_OTLP_INSECURE"

vault_kv_put cryptotax/tax-svc \
  APP_VERSION="$APP_VERSION" \
  APP_ENV="$APP_ENV" \
  DATABASE_URL="$TAX_DATABASE_URL" \
  AGGREGATION_SVC_ADDR="$AGGREGATION_SVC_ADDR" \
  REPORT_SVC_ADDR="$REPORT_SVC_ADDR" \
  MINIO_ENDPOINT="$MINIO_ENDPOINT" \
  MINIO_PUBLIC_BASE_URL="$MINIO_PUBLIC_BASE_URL" \
  MINIO_ACCESS_KEY="$MINIO_ACCESS_KEY" \
  MINIO_SECRET_KEY="$MINIO_SECRET_KEY" \
  OTEL_EXPORTER_OTLP_ENDPOINT="$OTEL_EXPORTER_OTLP_ENDPOINT" \
  OTEL_EXPORTER_OTLP_INSECURE="$OTEL_EXPORTER_OTLP_INSECURE"

vault_kv_put cryptotax/report-svc \
  APP_VERSION="$APP_VERSION" \
  APP_ENV="$APP_ENV" \
  MINIO_ENDPOINT="$MINIO_ENDPOINT" \
  MINIO_ACCESS_KEY="$MINIO_ACCESS_KEY" \
  MINIO_SECRET_KEY="$MINIO_SECRET_KEY" \
  OTEL_EXPORTER_OTLP_ENDPOINT="$OTEL_EXPORTER_OTLP_ENDPOINT" \
  OTEL_EXPORTER_OTLP_INSECURE="$OTEL_EXPORTER_OTLP_INSECURE"

vault_kv_put cryptotax/auth-svc \
  DATABASE_URL="$AUTH_DATABASE_URL" \
  DB_MAX_CONNS="$AUTH_DB_MAX_CONNS" \
  DB_CONN_TIMEOUT="$AUTH_DB_CONN_TIMEOUT" \
  REDIS_URL="$REDIS_URL" \
  REDIS_MAX_CONNS="$AUTH_REDIS_MAX_CONNS" \
  REDIS_SKEW_SECS="$AUTH_REDIS_SKEW_SECS" \
  JWT_LEEWAY_SECS="$AUTH_JWT_LEEWAY_SECS" \
  ACCESS_TTL_SECS="$AUTH_ACCESS_TTL_SECS" \
  REFRESH_TTL_SECS="$AUTH_REFRESH_TTL_SECS" \
  SMTP_HOST="$AUTH_SMTP_HOST" \
  SMTP_PORT="$AUTH_SMTP_PORT" \
  EMAIL="$AUTH_EMAIL" \
  EMAIL_PASSWORD="$AUTH_EMAIL_PASSWORD" \
  EMAIL_NAME="$AUTH_EMAIL_NAME" \
  SMTP_TIMEOUT="$AUTH_SMTP_TIMEOUT" \
  SMTP_MAX_RETRIES="$AUTH_SMTP_MAX_RETRIES" \
  PASSWORD_PEPPER="$AUTH_PASSWORD_PEPPER" \
  EMAIL_VERIFY_TTL_SECS="$AUTH_EMAIL_VERIFY_TTL_SECS" \
  DUMMY_PASSWORD_HASH="$AUTH_DUMMY_PASSWORD_HASH"

vault_kv_put cryptotax/ledger-svc \
  DATABASE_URL="$LEDGER_DATABASE_URL" \
  DB_MAX_CONNS="$LEDGER_DB_MAX_CONNS" \
  DB_CONN_TIMEOUT="$LEDGER_DB_CONN_TIMEOUT"

echo "local vault seeding finished"
