// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: fx_rates.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getFXRate = `-- name: GetFXRate :one
SELECT fiat, day, rate, is_real, source, updated_at
FROM fx_rates
WHERE fiat = $1
  AND day <= $2
ORDER BY day DESC
LIMIT 1
`

type GetFXRateParams struct {
	Fiat string      `json:"fiat"`
	Day  pgtype.Date `json:"day"`
}

func (q *Queries) GetFXRate(ctx context.Context, arg GetFXRateParams) (FxRate, error) {
	row := q.db.QueryRow(ctx, getFXRate, arg.Fiat, arg.Day)
	var i FxRate
	err := row.Scan(
		&i.Fiat,
		&i.Day,
		&i.Rate,
		&i.IsReal,
		&i.Source,
		&i.UpdatedAt,
	)
	return i, err
}

const listFXRatesByFiat = `-- name: ListFXRatesByFiat :many
SELECT fiat, day, rate, is_real, source, updated_at
FROM fx_rates
WHERE fiat = $1
ORDER BY day ASC
`

func (q *Queries) ListFXRatesByFiat(ctx context.Context, fiat string) ([]FxRate, error) {
	rows, err := q.db.Query(ctx, listFXRatesByFiat, fiat)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []FxRate
	for rows.Next() {
		var i FxRate
		if err := rows.Scan(
			&i.Fiat,
			&i.Day,
			&i.Rate,
			&i.IsReal,
			&i.Source,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertFXRate = `-- name: UpsertFXRate :exec
INSERT INTO fx_rates (fiat, day, rate, is_real, source)
VALUES ($1, $2, $3, $4, $5)
ON CONFLICT (fiat, day)
DO UPDATE SET
  rate = EXCLUDED.rate,
  is_real = EXCLUDED.is_real,
  source = EXCLUDED.source,
  updated_at = now()
`

type UpsertFXRateParams struct {
	Fiat   string         `json:"fiat"`
	Day    pgtype.Date    `json:"day"`
	Rate   pgtype.Numeric `json:"rate"`
	IsReal bool           `json:"isReal"`
	Source string         `json:"source"`
}

func (q *Queries) UpsertFXRate(ctx context.Context, arg UpsertFXRateParams) error {
	_, err := q.db.Exec(ctx, upsertFXRate,
		arg.Fiat,
		arg.Day,
		arg.Rate,
		arg.IsReal,
		arg.Source,
	)
	return err
}
