// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: historical_prices.sql

package db

import (
	"context"
	"time"

	"github.com/jackc/pgx/v5/pgtype"
)

const getHistoricalPrice = `-- name: GetHistoricalPrice :one
SELECT coin_id, bucket_start_utc, price_usd, granularity_seconds, fetched_at
FROM historical_prices
WHERE coin_id = $1
  AND bucket_start_utc = $2
`

type GetHistoricalPriceParams struct {
	CoinID         string    `json:"coin_id"`
	BucketStartUtc time.Time `json:"bucket_start_utc"`
}

func (q *Queries) GetHistoricalPrice(ctx context.Context, arg GetHistoricalPriceParams) (HistoricalPrice, error) {
	row := q.db.QueryRow(ctx, getHistoricalPrice, arg.CoinID, arg.BucketStartUtc)
	var i HistoricalPrice
	err := row.Scan(
		&i.CoinID,
		&i.BucketStartUtc,
		&i.PriceUsd,
		&i.GranularitySeconds,
		&i.FetchedAt,
	)
	return i, err
}

const getHistoricalPricesBatch = `-- name: GetHistoricalPricesBatch :many
WITH keys AS (
  SELECT c.coin_id, b.bucket_start_utc
  FROM unnest($1::text[]) WITH ORDINALITY AS c(coin_id, ord)
  JOIN unnest($2::timestamptz[]) WITH ORDINALITY AS b(bucket_start_utc, ord)
    USING (ord)
)
SELECT
  hp.coin_id,
  hp.bucket_start_utc,
  hp.price_usd,
  hp.granularity_seconds,
  hp.fetched_at
FROM historical_prices hp
JOIN keys k
  ON hp.coin_id = k.coin_id
 AND hp.bucket_start_utc = k.bucket_start_utc
`

type GetHistoricalPricesBatchParams struct {
	Column1 []string    `json:"column_1"`
	Column2 []time.Time `json:"column_2"`
}

func (q *Queries) GetHistoricalPricesBatch(ctx context.Context, arg GetHistoricalPricesBatchParams) ([]HistoricalPrice, error) {
	rows, err := q.db.Query(ctx, getHistoricalPricesBatch, arg.Column1, arg.Column2)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []HistoricalPrice{}
	for rows.Next() {
		var i HistoricalPrice
		if err := rows.Scan(
			&i.CoinID,
			&i.BucketStartUtc,
			&i.PriceUsd,
			&i.GranularitySeconds,
			&i.FetchedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertHistoricalPrice = `-- name: UpsertHistoricalPrice :exec
INSERT INTO historical_prices (coin_id, bucket_start_utc, price_usd, granularity_seconds, fetched_at)
VALUES ($1, $2, $3, $4, now())
ON CONFLICT (coin_id, bucket_start_utc)
DO UPDATE SET
  price_usd = EXCLUDED.price_usd,
  granularity_seconds = EXCLUDED.granularity_seconds,
  fetched_at = now()
WHERE EXCLUDED.granularity_seconds < historical_prices.granularity_seconds
`

type UpsertHistoricalPriceParams struct {
	CoinID             string         `json:"coin_id"`
	BucketStartUtc     time.Time      `json:"bucket_start_utc"`
	PriceUsd           pgtype.Numeric `json:"price_usd"`
	GranularitySeconds int32          `json:"granularity_seconds"`
}

func (q *Queries) UpsertHistoricalPrice(ctx context.Context, arg UpsertHistoricalPriceParams) error {
	_, err := q.db.Exec(ctx, upsertHistoricalPrice,
		arg.CoinID,
		arg.BucketStartUtc,
		arg.PriceUsd,
		arg.GranularitySeconds,
	)
	return err
}
