// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: historical_prices.sql

package db

import (
	"context"
	"time"

	"github.com/jackc/pgx/v5/pgtype"
)

const getHistoricalPrice = `-- name: GetHistoricalPrice :one
SELECT coin_id, fiat_currency, bucket_start_utc, source_profile, rate, fetched_at
FROM historical_prices
WHERE coin_id = $1
  AND fiat_currency = $2
  AND bucket_start_utc = $3
  AND source_profile = $4
`

type GetHistoricalPriceParams struct {
	CoinID         string    `json:"coin_id"`
	FiatCurrency   string    `json:"fiat_currency"`
	BucketStartUtc time.Time `json:"bucket_start_utc"`
	SourceProfile  string    `json:"source_profile"`
}

func (q *Queries) GetHistoricalPrice(ctx context.Context, arg GetHistoricalPriceParams) (HistoricalPrice, error) {
	row := q.db.QueryRow(ctx, getHistoricalPrice,
		arg.CoinID,
		arg.FiatCurrency,
		arg.BucketStartUtc,
		arg.SourceProfile,
	)
	var i HistoricalPrice
	err := row.Scan(
		&i.CoinID,
		&i.FiatCurrency,
		&i.BucketStartUtc,
		&i.SourceProfile,
		&i.Rate,
		&i.FetchedAt,
	)
	return i, err
}

const getHistoricalPricesBatch = `-- name: GetHistoricalPricesBatch :many
WITH keys AS (
  SELECT c.coin_id, b.bucket_start_utc
  FROM unnest($1::text[]) WITH ORDINALITY AS c(coin_id, ord)
  JOIN unnest($2::timestamptz[]) WITH ORDINALITY AS b(bucket_start_utc, ord)
    USING (ord)
)
SELECT
  hp.coin_id,
  hp.fiat_currency,
  hp.bucket_start_utc,
  hp.source_profile,
  hp.rate,
  hp.fetched_at
FROM historical_prices hp
JOIN keys k
  ON hp.coin_id = k.coin_id
 AND hp.bucket_start_utc = k.bucket_start_utc
WHERE hp.fiat_currency = $3
  AND hp.source_profile = $4
`

type GetHistoricalPricesBatchParams struct {
	Column1       []string    `json:"column_1"`
	Column2       []time.Time `json:"column_2"`
	FiatCurrency  string      `json:"fiat_currency"`
	SourceProfile string      `json:"source_profile"`
}

func (q *Queries) GetHistoricalPricesBatch(ctx context.Context, arg GetHistoricalPricesBatchParams) ([]HistoricalPrice, error) {
	rows, err := q.db.Query(ctx, getHistoricalPricesBatch,
		arg.Column1,
		arg.Column2,
		arg.FiatCurrency,
		arg.SourceProfile,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []HistoricalPrice{}
	for rows.Next() {
		var i HistoricalPrice
		if err := rows.Scan(
			&i.CoinID,
			&i.FiatCurrency,
			&i.BucketStartUtc,
			&i.SourceProfile,
			&i.Rate,
			&i.FetchedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertHistoricalPrice = `-- name: UpsertHistoricalPrice :exec
INSERT INTO historical_prices (coin_id, fiat_currency, bucket_start_utc, source_profile, rate)
VALUES ($1, $2, $3, $4, $5)
ON CONFLICT (coin_id, fiat_currency, bucket_start_utc, source_profile)
DO UPDATE SET rate = EXCLUDED.rate, fetched_at = now()
`

type UpsertHistoricalPriceParams struct {
	CoinID         string         `json:"coin_id"`
	FiatCurrency   string         `json:"fiat_currency"`
	BucketStartUtc time.Time      `json:"bucket_start_utc"`
	SourceProfile  string         `json:"source_profile"`
	Rate           pgtype.Numeric `json:"rate"`
}

func (q *Queries) UpsertHistoricalPrice(ctx context.Context, arg UpsertHistoricalPriceParams) error {
	_, err := q.db.Exec(ctx, upsertHistoricalPrice,
		arg.CoinID,
		arg.FiatCurrency,
		arg.BucketStartUtc,
		arg.SourceProfile,
		arg.Rate,
	)
	return err
}
