// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type HistoricalPrice struct {
	CoinID             string             `json:"coinId"`
	BucketStartUtc     pgtype.Timestamptz `json:"bucketStartUtc"`
	PriceUsd           pgtype.Numeric     `json:"priceUsd"`
	GranularitySeconds int32              `json:"granularitySeconds"`
	FetchedAt          pgtype.Timestamptz `json:"fetchedAt"`
}

type TenantSymbol struct {
	TenantID  uuid.UUID          `json:"tenantId"`
	Source    string             `json:"source"`
	Symbol    string             `json:"symbol"`
	CoinID    string             `json:"coinId"`
	CreatedAt pgtype.Timestamptz `json:"createdAt"`
	UpdatedAt pgtype.Timestamptz `json:"updatedAt"`
}
