// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"context"
)

type Querier interface {
	DeleteUserSymbol(ctx context.Context, arg DeleteUserSymbolParams) (int64, error)
	GetFXRate(ctx context.Context, arg GetFXRateParams) (FxRate, error)
	GetHistoricalPrice(ctx context.Context, arg GetHistoricalPriceParams) (HistoricalPrice, error)
	GetHistoricalPricesBatch(ctx context.Context, arg GetHistoricalPricesBatchParams) ([]GetHistoricalPricesBatchRow, error)
	GetUserSymbols(ctx context.Context, arg GetUserSymbolsParams) ([]UserSymbol, error)
	ListFXRatesByFiat(ctx context.Context, fiat string) ([]FxRate, error)
	ListUserSymbolsBySource(ctx context.Context, arg ListUserSymbolsBySourceParams) ([]UserSymbol, error)
	UpsertFXRate(ctx context.Context, arg UpsertFXRateParams) error
	UpsertHistoricalPrice(ctx context.Context, arg UpsertHistoricalPriceParams) error
	UpsertHistoricalPricesBatch(ctx context.Context, arg UpsertHistoricalPricesBatchParams) error
	UpsertUserSymbol(ctx context.Context, arg UpsertUserSymbolParams) error
}

var _ Querier = (*Queries)(nil)
