// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"context"
)

type Querier interface {
	DeleteTenantSymbolOverride(ctx context.Context, arg DeleteTenantSymbolOverrideParams) error
	GetHistoricalPrice(ctx context.Context, arg GetHistoricalPriceParams) (HistoricalPrice, error)
	GetHistoricalPricesBatch(ctx context.Context, arg GetHistoricalPricesBatchParams) ([]GetHistoricalPricesBatchRow, error)
	GetTenantSymbolOverridesBySymbols(ctx context.Context, arg GetTenantSymbolOverridesBySymbolsParams) ([]TenantSymbolOverride, error)
	ListTenantSymbolOverridesBySource(ctx context.Context, arg ListTenantSymbolOverridesBySourceParams) ([]TenantSymbolOverride, error)
	UpsertHistoricalPrice(ctx context.Context, arg UpsertHistoricalPriceParams) error
	UpsertTenantSymbolOverride(ctx context.Context, arg UpsertTenantSymbolOverrideParams) error
}

var _ Querier = (*Queries)(nil)
