// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"context"
)

type Querier interface {
	DeleteTenantSymbol(ctx context.Context, arg DeleteTenantSymbolParams) error
	GetHistoricalPrice(ctx context.Context, arg GetHistoricalPriceParams) (HistoricalPrice, error)
	GetHistoricalPricesBatch(ctx context.Context, arg GetHistoricalPricesBatchParams) ([]HistoricalPrice, error)
	GetTenantSymbols(ctx context.Context, arg GetTenantSymbolsParams) ([]TenantSymbol, error)
	ListTenantSymbolsBySource(ctx context.Context, arg ListTenantSymbolsBySourceParams) ([]TenantSymbol, error)
	UpsertHistoricalPrice(ctx context.Context, arg UpsertHistoricalPriceParams) error
	UpsertTenantSymbol(ctx context.Context, arg UpsertTenantSymbolParams) error
}

var _ Querier = (*Queries)(nil)
