// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: tenant_symbol_overrides.sql

package db

import (
	"context"

	"github.com/google/uuid"
)

const deleteTenantSymbolOverride = `-- name: DeleteTenantSymbolOverride :exec
DELETE FROM tenant_symbol_overrides
WHERE tenant_id = $1 AND source = $2 AND symbol = $3
`

type DeleteTenantSymbolOverrideParams struct {
	TenantID uuid.UUID `json:"tenant_id"`
	Source   string    `json:"source"`
	Symbol   string    `json:"symbol"`
}

func (q *Queries) DeleteTenantSymbolOverride(ctx context.Context, arg DeleteTenantSymbolOverrideParams) error {
	_, err := q.db.Exec(ctx, deleteTenantSymbolOverride, arg.TenantID, arg.Source, arg.Symbol)
	return err
}

const getTenantSymbolOverridesBySymbols = `-- name: GetTenantSymbolOverridesBySymbols :many
SELECT tenant_id, source, symbol, coin_id, created_at, updated_at
FROM tenant_symbol_overrides
WHERE tenant_id = $1
  AND source = $2
  AND symbol = ANY($3::text[])
`

type GetTenantSymbolOverridesBySymbolsParams struct {
	TenantID uuid.UUID `json:"tenant_id"`
	Source   string    `json:"source"`
	Column3  []string  `json:"column_3"`
}

func (q *Queries) GetTenantSymbolOverridesBySymbols(ctx context.Context, arg GetTenantSymbolOverridesBySymbolsParams) ([]TenantSymbolOverride, error) {
	rows, err := q.db.Query(ctx, getTenantSymbolOverridesBySymbols, arg.TenantID, arg.Source, arg.Column3)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []TenantSymbolOverride{}
	for rows.Next() {
		var i TenantSymbolOverride
		if err := rows.Scan(
			&i.TenantID,
			&i.Source,
			&i.Symbol,
			&i.CoinID,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTenantSymbolOverridesBySource = `-- name: ListTenantSymbolOverridesBySource :many
SELECT tenant_id, source, symbol, coin_id, created_at, updated_at
FROM tenant_symbol_overrides
WHERE tenant_id = $1
  AND source = $2
ORDER BY symbol ASC
`

type ListTenantSymbolOverridesBySourceParams struct {
	TenantID uuid.UUID `json:"tenant_id"`
	Source   string    `json:"source"`
}

func (q *Queries) ListTenantSymbolOverridesBySource(ctx context.Context, arg ListTenantSymbolOverridesBySourceParams) ([]TenantSymbolOverride, error) {
	rows, err := q.db.Query(ctx, listTenantSymbolOverridesBySource, arg.TenantID, arg.Source)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []TenantSymbolOverride{}
	for rows.Next() {
		var i TenantSymbolOverride
		if err := rows.Scan(
			&i.TenantID,
			&i.Source,
			&i.Symbol,
			&i.CoinID,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertTenantSymbolOverride = `-- name: UpsertTenantSymbolOverride :exec
INSERT INTO tenant_symbol_overrides (tenant_id, source, symbol, coin_id)
VALUES ($1, $2, $3, $4)
ON CONFLICT (tenant_id, source, symbol)
DO UPDATE SET coin_id = EXCLUDED.coin_id, updated_at = now()
`

type UpsertTenantSymbolOverrideParams struct {
	TenantID uuid.UUID `json:"tenant_id"`
	Source   string    `json:"source"`
	Symbol   string    `json:"symbol"`
	CoinID   string    `json:"coin_id"`
}

func (q *Queries) UpsertTenantSymbolOverride(ctx context.Context, arg UpsertTenantSymbolOverrideParams) error {
	_, err := q.db.Exec(ctx, upsertTenantSymbolOverride,
		arg.TenantID,
		arg.Source,
		arg.Symbol,
		arg.CoinID,
	)
	return err
}
