// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: tenant_symbols.sql

package db

import (
	"context"

	"github.com/google/uuid"
)

const deleteTenantSymbol = `-- name: DeleteTenantSymbol :execrows
DELETE FROM tenant_symbols
WHERE tenant_id = $1 AND source = $2 AND symbol = $3
`

type DeleteTenantSymbolParams struct {
	TenantID uuid.UUID `json:"tenant_id"`
	Source   string    `json:"source"`
	Symbol   string    `json:"symbol"`
}

func (q *Queries) DeleteTenantSymbol(ctx context.Context, arg DeleteTenantSymbolParams) (int64, error) {
	result, err := q.db.Exec(ctx, deleteTenantSymbol, arg.TenantID, arg.Source, arg.Symbol)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getTenantSymbols = `-- name: GetTenantSymbols :many
SELECT tenant_id, source, symbol, coin_id, created_at, updated_at
FROM tenant_symbols
WHERE tenant_id = $1
  AND source = $2
  AND symbol = ANY($3::text[])
`

type GetTenantSymbolsParams struct {
	TenantID uuid.UUID `json:"tenant_id"`
	Source   string    `json:"source"`
	Column3  []string  `json:"column_3"`
}

func (q *Queries) GetTenantSymbols(ctx context.Context, arg GetTenantSymbolsParams) ([]TenantSymbol, error) {
	rows, err := q.db.Query(ctx, getTenantSymbols, arg.TenantID, arg.Source, arg.Column3)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []TenantSymbol{}
	for rows.Next() {
		var i TenantSymbol
		if err := rows.Scan(
			&i.TenantID,
			&i.Source,
			&i.Symbol,
			&i.CoinID,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTenantSymbolsBySource = `-- name: ListTenantSymbolsBySource :many
SELECT tenant_id, source, symbol, coin_id, created_at, updated_at
FROM tenant_symbols
WHERE tenant_id = $1
  AND source = $2
ORDER BY symbol ASC
`

type ListTenantSymbolsBySourceParams struct {
	TenantID uuid.UUID `json:"tenant_id"`
	Source   string    `json:"source"`
}

func (q *Queries) ListTenantSymbolsBySource(ctx context.Context, arg ListTenantSymbolsBySourceParams) ([]TenantSymbol, error) {
	rows, err := q.db.Query(ctx, listTenantSymbolsBySource, arg.TenantID, arg.Source)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []TenantSymbol{}
	for rows.Next() {
		var i TenantSymbol
		if err := rows.Scan(
			&i.TenantID,
			&i.Source,
			&i.Symbol,
			&i.CoinID,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertTenantSymbol = `-- name: UpsertTenantSymbol :exec
INSERT INTO tenant_symbols (tenant_id, source, symbol, coin_id)
VALUES ($1, $2, $3, $4)
ON CONFLICT (tenant_id, source, symbol)
DO UPDATE SET coin_id = EXCLUDED.coin_id, updated_at = now()
`

type UpsertTenantSymbolParams struct {
	TenantID uuid.UUID `json:"tenant_id"`
	Source   string    `json:"source"`
	Symbol   string    `json:"symbol"`
	CoinID   string    `json:"coin_id"`
}

func (q *Queries) UpsertTenantSymbol(ctx context.Context, arg UpsertTenantSymbolParams) error {
	_, err := q.db.Exec(ctx, upsertTenantSymbol,
		arg.TenantID,
		arg.Source,
		arg.Symbol,
		arg.CoinID,
	)
	return err
}
