// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: user_symbols.sql

package db

import (
	"context"

	"github.com/google/uuid"
)

const deleteUserSymbol = `-- name: DeleteUserSymbol :execrows
DELETE FROM user_symbols
WHERE user_id = $1 AND source = $2 AND symbol = $3
`

type DeleteUserSymbolParams struct {
	UserID uuid.UUID `json:"userId"`
	Source string    `json:"source"`
	Symbol string    `json:"symbol"`
}

func (q *Queries) DeleteUserSymbol(ctx context.Context, arg DeleteUserSymbolParams) (int64, error) {
	result, err := q.db.Exec(ctx, deleteUserSymbol, arg.UserID, arg.Source, arg.Symbol)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getUserSymbols = `-- name: GetUserSymbols :many
SELECT user_id, source, symbol, coin_id, created_at, updated_at
FROM user_symbols
WHERE user_id = $1
  AND source = $2
  AND symbol = ANY($3::text[])
`

type GetUserSymbolsParams struct {
	UserID  uuid.UUID `json:"userId"`
	Source  string    `json:"source"`
	Column3 []string  `json:"column3"`
}

func (q *Queries) GetUserSymbols(ctx context.Context, arg GetUserSymbolsParams) ([]UserSymbol, error) {
	rows, err := q.db.Query(ctx, getUserSymbols, arg.UserID, arg.Source, arg.Column3)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []UserSymbol
	for rows.Next() {
		var i UserSymbol
		if err := rows.Scan(
			&i.UserID,
			&i.Source,
			&i.Symbol,
			&i.CoinID,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUserSymbolsBySource = `-- name: ListUserSymbolsBySource :many
SELECT user_id, source, symbol, coin_id, created_at, updated_at
FROM user_symbols
WHERE user_id = $1
  AND source = $2
ORDER BY symbol ASC
`

type ListUserSymbolsBySourceParams struct {
	UserID uuid.UUID `json:"userId"`
	Source string    `json:"source"`
}

func (q *Queries) ListUserSymbolsBySource(ctx context.Context, arg ListUserSymbolsBySourceParams) ([]UserSymbol, error) {
	rows, err := q.db.Query(ctx, listUserSymbolsBySource, arg.UserID, arg.Source)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []UserSymbol
	for rows.Next() {
		var i UserSymbol
		if err := rows.Scan(
			&i.UserID,
			&i.Source,
			&i.Symbol,
			&i.CoinID,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertUserSymbol = `-- name: UpsertUserSymbol :exec
INSERT INTO user_symbols (user_id, source, symbol, coin_id)
VALUES ($1, $2, $3, $4)
ON CONFLICT (user_id, source, symbol)
DO UPDATE SET coin_id = EXCLUDED.coin_id, updated_at = now()
`

type UpsertUserSymbolParams struct {
	UserID uuid.UUID `json:"userId"`
	Source string    `json:"source"`
	Symbol string    `json:"symbol"`
	CoinID string    `json:"coinId"`
}

func (q *Queries) UpsertUserSymbol(ctx context.Context, arg UpsertUserSymbolParams) error {
	_, err := q.db.Exec(ctx, upsertUserSymbol,
		arg.UserID,
		arg.Source,
		arg.Symbol,
		arg.CoinID,
	)
	return err
}
