// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type TaxJob struct {
	ID               uuid.UUID          `json:"id"`
	UserID           uuid.UUID          `json:"userId"`
	TaxYear          int32              `json:"taxYear"`
	PolicySnapshot   []byte             `json:"policySnapshot"`
	Status           string             `json:"status"`
	Attempts         int32              `json:"attempts"`
	RetryAt          pgtype.Timestamptz `json:"retryAt"`
	Summary          []byte             `json:"summary"`
	AuditObjectKey   *string            `json:"auditObjectKey"`
	ReportObjectKey  *string            `json:"reportObjectKey"`
	CreatedAt        pgtype.Timestamptz `json:"createdAt"`
	StartedAt        pgtype.Timestamptz `json:"startedAt"`
	FinishedAt       pgtype.Timestamptz `json:"finishedAt"`
	LastErrorCode    *string            `json:"lastErrorCode"`
	LastErrorMessage *string            `json:"lastErrorMessage"`
}

type TaxProfile struct {
	UserID             uuid.UUID          `json:"userId"`
	Inn                string             `json:"inn"`
	Oktmo              string             `json:"oktmo"`
	LastName           string             `json:"lastName"`
	FirstName          string             `json:"firstName"`
	MiddleName         string             `json:"middleName"`
	Timezone           string             `json:"timezone"`
	Phone              string             `json:"phone"`
	Wallets            []byte             `json:"wallets"`
	TaxResidencyStatus string             `json:"taxResidencyStatus"`
	TaxpayerType       string             `json:"taxpayerType"`
	CreatedAt          pgtype.Timestamptz `json:"createdAt"`
	UpdatedAt          pgtype.Timestamptz `json:"updatedAt"`
}
