// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"context"

	"github.com/google/uuid"
)

type Querier interface {
	ClaimNextQueuedTaxJob(ctx context.Context) (TaxJob, error)
	CountTaxJobs(ctx context.Context, tenantID uuid.UUID) (int64, error)
	CreateTaxJob(ctx context.Context, arg CreateTaxJobParams) (TaxJob, error)
	DeleteTaxProfile(ctx context.Context, tenantID uuid.UUID) (int64, error)
	GetTaxJob(ctx context.Context, arg GetTaxJobParams) (TaxJob, error)
	GetTaxProfile(ctx context.Context, tenantID uuid.UUID) (TaxProfile, error)
	ListTaxJobs(ctx context.Context, arg ListTaxJobsParams) ([]TaxJob, error)
	MarkTaxJobCanceled(ctx context.Context, id uuid.UUID) error
	MarkTaxJobFailed(ctx context.Context, arg MarkTaxJobFailedParams) error
	RequeueTaxJob(ctx context.Context, arg RequeueTaxJobParams) error
	SaveTaxJobResult(ctx context.Context, arg SaveTaxJobResultParams) error
	UpsertTaxProfile(ctx context.Context, arg UpsertTaxProfileParams) (TaxProfile, error)
}

var _ Querier = (*Queries)(nil)
