// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: tax_profile.sql

package db

import (
	"context"

	"github.com/google/uuid"
)

const deleteTaxProfile = `-- name: DeleteTaxProfile :execrows
DELETE FROM tax_profile
WHERE tenant_id = $1
`

func (q *Queries) DeleteTaxProfile(ctx context.Context, tenantID uuid.UUID) (int64, error) {
	result, err := q.db.Exec(ctx, deleteTaxProfile, tenantID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getTaxProfile = `-- name: GetTaxProfile :one
SELECT
  tenant_id,
  inn,
  last_name,
  first_name,
  middle_name,
  timezone,
  phone,
  wallets,
  tax_residency_status,
  taxpayer_type,
  created_at,
  updated_at
FROM tax_profile
WHERE tenant_id = $1
`

func (q *Queries) GetTaxProfile(ctx context.Context, tenantID uuid.UUID) (TaxProfile, error) {
	row := q.db.QueryRow(ctx, getTaxProfile, tenantID)
	var i TaxProfile
	err := row.Scan(
		&i.TenantID,
		&i.Inn,
		&i.LastName,
		&i.FirstName,
		&i.MiddleName,
		&i.Timezone,
		&i.Phone,
		&i.Wallets,
		&i.TaxResidencyStatus,
		&i.TaxpayerType,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const upsertTaxProfile = `-- name: UpsertTaxProfile :one
INSERT INTO tax_profile (
  tenant_id,
  inn,
  last_name,
  first_name,
  middle_name,
  timezone,
  phone,
  wallets,
  tax_residency_status,
  taxpayer_type
)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10)
ON CONFLICT (tenant_id)
DO UPDATE SET
  inn = EXCLUDED.inn,
  last_name = EXCLUDED.last_name,
  first_name = EXCLUDED.first_name,
  middle_name = EXCLUDED.middle_name,
  timezone = EXCLUDED.timezone,
  phone = EXCLUDED.phone,
  wallets = EXCLUDED.wallets,
  tax_residency_status = EXCLUDED.tax_residency_status,
  taxpayer_type = EXCLUDED.taxpayer_type,
  updated_at = now()
RETURNING
  tenant_id,
  inn,
  last_name,
  first_name,
  middle_name,
  timezone,
  phone,
  wallets,
  tax_residency_status,
  taxpayer_type,
  created_at,
  updated_at
`

type UpsertTaxProfileParams struct {
	TenantID           uuid.UUID `json:"tenantId"`
	Inn                string    `json:"inn"`
	LastName           string    `json:"lastName"`
	FirstName          string    `json:"firstName"`
	MiddleName         string    `json:"middleName"`
	Timezone           string    `json:"timezone"`
	Phone              string    `json:"phone"`
	Wallets            []byte    `json:"wallets"`
	TaxResidencyStatus string    `json:"taxResidencyStatus"`
	TaxpayerType       string    `json:"taxpayerType"`
}

func (q *Queries) UpsertTaxProfile(ctx context.Context, arg UpsertTaxProfileParams) (TaxProfile, error) {
	row := q.db.QueryRow(ctx, upsertTaxProfile,
		arg.TenantID,
		arg.Inn,
		arg.LastName,
		arg.FirstName,
		arg.MiddleName,
		arg.Timezone,
		arg.Phone,
		arg.Wallets,
		arg.TaxResidencyStatus,
		arg.TaxpayerType,
	)
	var i TaxProfile
	err := row.Scan(
		&i.TenantID,
		&i.Inn,
		&i.LastName,
		&i.FirstName,
		&i.MiddleName,
		&i.Timezone,
		&i.Phone,
		&i.Wallets,
		&i.TaxResidencyStatus,
		&i.TaxpayerType,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
