// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: tax_jobs.sql

package db

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const claimNextQueuedTaxJob = `-- name: ClaimNextQueuedTaxJob :one
WITH next_job AS (
  SELECT id
  FROM tax_jobs
  WHERE status = 'queued' AND retry_at <= now()
  ORDER BY retry_at ASC, created_at ASC
  FOR UPDATE SKIP LOCKED
  LIMIT 1
)
UPDATE tax_jobs AS j
SET
  status = 'running',
  attempts = j.attempts + 1,
  started_at = now(),
  retry_at = now(),
  finished_at = NULL,
  last_error_code = NULL,
  last_error_message = NULL
FROM next_job
WHERE j.id = next_job.id
RETURNING
  j.id,
  j.tenant_id,
  j.tax_year,
  j.policy_snapshot,
  j.status,
  j.attempts,
  j.retry_at,
  j.summary,
  j.audit_object_key,
  j.report_object_key,
  j.created_at,
  j.started_at,
  j.finished_at,
  j.last_error_code,
  j.last_error_message
`

func (q *Queries) ClaimNextQueuedTaxJob(ctx context.Context) (TaxJob, error) {
	row := q.db.QueryRow(ctx, claimNextQueuedTaxJob)
	var i TaxJob
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.TaxYear,
		&i.PolicySnapshot,
		&i.Status,
		&i.Attempts,
		&i.RetryAt,
		&i.Summary,
		&i.AuditObjectKey,
		&i.ReportObjectKey,
		&i.CreatedAt,
		&i.StartedAt,
		&i.FinishedAt,
		&i.LastErrorCode,
		&i.LastErrorMessage,
	)
	return i, err
}

const countTaxJobs = `-- name: CountTaxJobs :one
SELECT count(*)
FROM tax_jobs
WHERE tenant_id = $1
`

func (q *Queries) CountTaxJobs(ctx context.Context, tenantID uuid.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countTaxJobs, tenantID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createTaxJob = `-- name: CreateTaxJob :one
INSERT INTO tax_jobs (
  id,
  tenant_id,
  tax_year,
  policy_snapshot,
  status,
  attempts,
  retry_at
)
VALUES ($1, $2, $3, $4, $5, $6, now())
RETURNING
  id,
  tenant_id,
  tax_year,
  policy_snapshot,
  status,
  attempts,
  retry_at,
  summary,
  audit_object_key,
  report_object_key,
  created_at,
  started_at,
  finished_at,
  last_error_code,
  last_error_message
`

type CreateTaxJobParams struct {
	ID             uuid.UUID `json:"id"`
	TenantID       uuid.UUID `json:"tenantId"`
	TaxYear        int32     `json:"taxYear"`
	PolicySnapshot []byte    `json:"policySnapshot"`
	Status         string    `json:"status"`
	Attempts       int32     `json:"attempts"`
}

func (q *Queries) CreateTaxJob(ctx context.Context, arg CreateTaxJobParams) (TaxJob, error) {
	row := q.db.QueryRow(ctx, createTaxJob,
		arg.ID,
		arg.TenantID,
		arg.TaxYear,
		arg.PolicySnapshot,
		arg.Status,
		arg.Attempts,
	)
	var i TaxJob
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.TaxYear,
		&i.PolicySnapshot,
		&i.Status,
		&i.Attempts,
		&i.RetryAt,
		&i.Summary,
		&i.AuditObjectKey,
		&i.ReportObjectKey,
		&i.CreatedAt,
		&i.StartedAt,
		&i.FinishedAt,
		&i.LastErrorCode,
		&i.LastErrorMessage,
	)
	return i, err
}

const getTaxJob = `-- name: GetTaxJob :one
SELECT
  id,
  tenant_id,
  tax_year,
  policy_snapshot,
  status,
  attempts,
  retry_at,
  summary,
  audit_object_key,
  report_object_key,
  created_at,
  started_at,
  finished_at,
  last_error_code,
  last_error_message
FROM tax_jobs
WHERE tenant_id = $1 AND id = $2
`

type GetTaxJobParams struct {
	TenantID uuid.UUID `json:"tenantId"`
	ID       uuid.UUID `json:"id"`
}

func (q *Queries) GetTaxJob(ctx context.Context, arg GetTaxJobParams) (TaxJob, error) {
	row := q.db.QueryRow(ctx, getTaxJob, arg.TenantID, arg.ID)
	var i TaxJob
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.TaxYear,
		&i.PolicySnapshot,
		&i.Status,
		&i.Attempts,
		&i.RetryAt,
		&i.Summary,
		&i.AuditObjectKey,
		&i.ReportObjectKey,
		&i.CreatedAt,
		&i.StartedAt,
		&i.FinishedAt,
		&i.LastErrorCode,
		&i.LastErrorMessage,
	)
	return i, err
}

const listTaxJobs = `-- name: ListTaxJobs :many
SELECT
  id,
  tenant_id,
  tax_year,
  policy_snapshot,
  status,
  attempts,
  retry_at,
  summary,
  audit_object_key,
  report_object_key,
  created_at,
  started_at,
  finished_at,
  last_error_code,
  last_error_message
FROM tax_jobs
WHERE tenant_id = $1
ORDER BY created_at DESC
LIMIT $2 OFFSET $3
`

type ListTaxJobsParams struct {
	TenantID uuid.UUID `json:"tenantId"`
	Limit    int32     `json:"limit"`
	Offset   int32     `json:"offset"`
}

func (q *Queries) ListTaxJobs(ctx context.Context, arg ListTaxJobsParams) ([]TaxJob, error) {
	rows, err := q.db.Query(ctx, listTaxJobs, arg.TenantID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []TaxJob
	for rows.Next() {
		var i TaxJob
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.TaxYear,
			&i.PolicySnapshot,
			&i.Status,
			&i.Attempts,
			&i.RetryAt,
			&i.Summary,
			&i.AuditObjectKey,
			&i.ReportObjectKey,
			&i.CreatedAt,
			&i.StartedAt,
			&i.FinishedAt,
			&i.LastErrorCode,
			&i.LastErrorMessage,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markTaxJobCanceled = `-- name: MarkTaxJobCanceled :exec
UPDATE tax_jobs
SET
  status = 'canceled',
  finished_at = now()
WHERE id = $1
`

func (q *Queries) MarkTaxJobCanceled(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, markTaxJobCanceled, id)
	return err
}

const markTaxJobFailed = `-- name: MarkTaxJobFailed :exec
UPDATE tax_jobs
SET
  status = 'failed',
  retry_at = now(),
  finished_at = now(),
  last_error_code = $2,
  last_error_message = $3
WHERE id = $1
`

type MarkTaxJobFailedParams struct {
	ID               uuid.UUID `json:"id"`
	LastErrorCode    *string   `json:"lastErrorCode"`
	LastErrorMessage *string   `json:"lastErrorMessage"`
}

func (q *Queries) MarkTaxJobFailed(ctx context.Context, arg MarkTaxJobFailedParams) error {
	_, err := q.db.Exec(ctx, markTaxJobFailed, arg.ID, arg.LastErrorCode, arg.LastErrorMessage)
	return err
}

const requeueTaxJob = `-- name: RequeueTaxJob :exec
UPDATE tax_jobs
SET
  status = 'queued',
  retry_at = $2,
  started_at = NULL,
  finished_at = NULL,
  last_error_code = $3,
  last_error_message = $4
WHERE id = $1
`

type RequeueTaxJobParams struct {
	ID               uuid.UUID          `json:"id"`
	RetryAt          pgtype.Timestamptz `json:"retryAt"`
	LastErrorCode    *string            `json:"lastErrorCode"`
	LastErrorMessage *string            `json:"lastErrorMessage"`
}

func (q *Queries) RequeueTaxJob(ctx context.Context, arg RequeueTaxJobParams) error {
	_, err := q.db.Exec(ctx, requeueTaxJob,
		arg.ID,
		arg.RetryAt,
		arg.LastErrorCode,
		arg.LastErrorMessage,
	)
	return err
}

const saveTaxJobResult = `-- name: SaveTaxJobResult :exec
UPDATE tax_jobs
SET
  status = 'success',
  summary = $2,
  audit_object_key = $3,
  report_object_key = $4,
  retry_at = now(),
  finished_at = now(),
  last_error_code = NULL,
  last_error_message = NULL
WHERE id = $1
`

type SaveTaxJobResultParams struct {
	ID              uuid.UUID `json:"id"`
	Summary         []byte    `json:"summary"`
	AuditObjectKey  *string   `json:"auditObjectKey"`
	ReportObjectKey *string   `json:"reportObjectKey"`
}

func (q *Queries) SaveTaxJobResult(ctx context.Context, arg SaveTaxJobResultParams) error {
	_, err := q.db.Exec(ctx, saveTaxJobResult,
		arg.ID,
		arg.Summary,
		arg.AuditObjectKey,
		arg.ReportObjectKey,
	)
	return err
}
