// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: tax_profile.sql

package db

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const getTaxProfile = `-- name: GetTaxProfile :one
SELECT
  tenant_id,
  jurisdiction,
  cost_basis_method,
  timezone,
  treat_swap_as_disposition,
  treat_crypto_fee_as_disposition,
  include_income_events,
  allow_loss_events_deduction,
  fail_on_negative_inventory,
  fail_on_missing_fiat,
  created_at,
  updated_at
FROM tax_profile
WHERE tenant_id = $1
`

type GetTaxProfileRow struct {
	TenantID                    uuid.UUID          `json:"tenantId"`
	Jurisdiction                string             `json:"jurisdiction"`
	CostBasisMethod             string             `json:"costBasisMethod"`
	Timezone                    string             `json:"timezone"`
	TreatSwapAsDisposition      bool               `json:"treatSwapAsDisposition"`
	TreatCryptoFeeAsDisposition bool               `json:"treatCryptoFeeAsDisposition"`
	IncludeIncomeEvents         bool               `json:"includeIncomeEvents"`
	AllowLossEventsDeduction    bool               `json:"allowLossEventsDeduction"`
	FailOnNegativeInventory     bool               `json:"failOnNegativeInventory"`
	FailOnMissingFiat           bool               `json:"failOnMissingFiat"`
	CreatedAt                   pgtype.Timestamptz `json:"createdAt"`
	UpdatedAt                   pgtype.Timestamptz `json:"updatedAt"`
}

func (q *Queries) GetTaxProfile(ctx context.Context, tenantID uuid.UUID) (GetTaxProfileRow, error) {
	row := q.db.QueryRow(ctx, getTaxProfile, tenantID)
	var i GetTaxProfileRow
	err := row.Scan(
		&i.TenantID,
		&i.Jurisdiction,
		&i.CostBasisMethod,
		&i.Timezone,
		&i.TreatSwapAsDisposition,
		&i.TreatCryptoFeeAsDisposition,
		&i.IncludeIncomeEvents,
		&i.AllowLossEventsDeduction,
		&i.FailOnNegativeInventory,
		&i.FailOnMissingFiat,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const upsertTaxProfile = `-- name: UpsertTaxProfile :one
INSERT INTO tax_profile (
  tenant_id, jurisdiction, cost_basis_method, timezone,
  treat_swap_as_disposition, treat_crypto_fee_as_disposition, include_income_events,
  allow_loss_events_deduction, fail_on_negative_inventory, fail_on_missing_fiat
)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10)
ON CONFLICT (tenant_id)
DO UPDATE SET
  jurisdiction = EXCLUDED.jurisdiction,
  cost_basis_method = EXCLUDED.cost_basis_method,
  treat_swap_as_disposition = EXCLUDED.treat_swap_as_disposition,
  treat_crypto_fee_as_disposition = EXCLUDED.treat_crypto_fee_as_disposition,
  include_income_events = EXCLUDED.include_income_events,
  allow_loss_events_deduction = EXCLUDED.allow_loss_events_deduction,
  fail_on_negative_inventory = EXCLUDED.fail_on_negative_inventory,
  fail_on_missing_fiat = EXCLUDED.fail_on_missing_fiat,
  timezone = EXCLUDED.timezone,
  updated_at = now()
RETURNING
  tenant_id,
  jurisdiction,
  cost_basis_method,
  timezone,
  treat_swap_as_disposition,
  treat_crypto_fee_as_disposition,
  include_income_events,
  allow_loss_events_deduction,
  fail_on_negative_inventory,
  fail_on_missing_fiat,
  created_at,
  updated_at
`

type UpsertTaxProfileParams struct {
	TenantID                    uuid.UUID `json:"tenantId"`
	Jurisdiction                string    `json:"jurisdiction"`
	CostBasisMethod             string    `json:"costBasisMethod"`
	Timezone                    string    `json:"timezone"`
	TreatSwapAsDisposition      bool      `json:"treatSwapAsDisposition"`
	TreatCryptoFeeAsDisposition bool      `json:"treatCryptoFeeAsDisposition"`
	IncludeIncomeEvents         bool      `json:"includeIncomeEvents"`
	AllowLossEventsDeduction    bool      `json:"allowLossEventsDeduction"`
	FailOnNegativeInventory     bool      `json:"failOnNegativeInventory"`
	FailOnMissingFiat           bool      `json:"failOnMissingFiat"`
}

type UpsertTaxProfileRow struct {
	TenantID                    uuid.UUID          `json:"tenantId"`
	Jurisdiction                string             `json:"jurisdiction"`
	CostBasisMethod             string             `json:"costBasisMethod"`
	Timezone                    string             `json:"timezone"`
	TreatSwapAsDisposition      bool               `json:"treatSwapAsDisposition"`
	TreatCryptoFeeAsDisposition bool               `json:"treatCryptoFeeAsDisposition"`
	IncludeIncomeEvents         bool               `json:"includeIncomeEvents"`
	AllowLossEventsDeduction    bool               `json:"allowLossEventsDeduction"`
	FailOnNegativeInventory     bool               `json:"failOnNegativeInventory"`
	FailOnMissingFiat           bool               `json:"failOnMissingFiat"`
	CreatedAt                   pgtype.Timestamptz `json:"createdAt"`
	UpdatedAt                   pgtype.Timestamptz `json:"updatedAt"`
}

func (q *Queries) UpsertTaxProfile(ctx context.Context, arg UpsertTaxProfileParams) (UpsertTaxProfileRow, error) {
	row := q.db.QueryRow(ctx, upsertTaxProfile,
		arg.TenantID,
		arg.Jurisdiction,
		arg.CostBasisMethod,
		arg.Timezone,
		arg.TreatSwapAsDisposition,
		arg.TreatCryptoFeeAsDisposition,
		arg.IncludeIncomeEvents,
		arg.AllowLossEventsDeduction,
		arg.FailOnNegativeInventory,
		arg.FailOnMissingFiat,
	)
	var i UpsertTaxProfileRow
	err := row.Scan(
		&i.TenantID,
		&i.Jurisdiction,
		&i.CostBasisMethod,
		&i.Timezone,
		&i.TreatSwapAsDisposition,
		&i.TreatCryptoFeeAsDisposition,
		&i.IncludeIncomeEvents,
		&i.AllowLossEventsDeduction,
		&i.FailOnNegativeInventory,
		&i.FailOnMissingFiat,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
