// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: tax_report_jobs.sql

package db

import (
	"context"

	"github.com/google/uuid"
)

const countTaxReportJobs = `-- name: CountTaxReportJobs :one
SELECT count(*)
FROM tax_report_jobs
WHERE tenant_id = $1 AND ($2 = 0 OR tax_year = $2)
`

type CountTaxReportJobsParams struct {
	TenantID uuid.UUID   `json:"tenantId"`
	Column2  interface{} `json:"column2"`
}

func (q *Queries) CountTaxReportJobs(ctx context.Context, arg CountTaxReportJobsParams) (int64, error) {
	row := q.db.QueryRow(ctx, countTaxReportJobs, arg.TenantID, arg.Column2)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createTaxReportJob = `-- name: CreateTaxReportJob :one
INSERT INTO tax_report_jobs (
  id, tenant_id, tax_year, jurisdiction, status, params
)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING
  id, tenant_id, tax_year, jurisdiction, status, requested_at, started_at, completed_at,
  error, params, summary, dataset_object_key, pdf_object_key
`

type CreateTaxReportJobParams struct {
	ID           uuid.UUID `json:"id"`
	TenantID     uuid.UUID `json:"tenantId"`
	TaxYear      int32     `json:"taxYear"`
	Jurisdiction string    `json:"jurisdiction"`
	Status       string    `json:"status"`
	Params       []byte    `json:"params"`
}

func (q *Queries) CreateTaxReportJob(ctx context.Context, arg CreateTaxReportJobParams) (TaxReportJob, error) {
	row := q.db.QueryRow(ctx, createTaxReportJob,
		arg.ID,
		arg.TenantID,
		arg.TaxYear,
		arg.Jurisdiction,
		arg.Status,
		arg.Params,
	)
	var i TaxReportJob
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.TaxYear,
		&i.Jurisdiction,
		&i.Status,
		&i.RequestedAt,
		&i.StartedAt,
		&i.CompletedAt,
		&i.Error,
		&i.Params,
		&i.Summary,
		&i.DatasetObjectKey,
		&i.PdfObjectKey,
	)
	return i, err
}

const getTaxReportJob = `-- name: GetTaxReportJob :one
SELECT
  id, tenant_id, tax_year, jurisdiction, status, requested_at, started_at, completed_at,
  error, params, summary, dataset_object_key, pdf_object_key
FROM tax_report_jobs
WHERE tenant_id = $1 AND id = $2
`

type GetTaxReportJobParams struct {
	TenantID uuid.UUID `json:"tenantId"`
	ID       uuid.UUID `json:"id"`
}

func (q *Queries) GetTaxReportJob(ctx context.Context, arg GetTaxReportJobParams) (TaxReportJob, error) {
	row := q.db.QueryRow(ctx, getTaxReportJob, arg.TenantID, arg.ID)
	var i TaxReportJob
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.TaxYear,
		&i.Jurisdiction,
		&i.Status,
		&i.RequestedAt,
		&i.StartedAt,
		&i.CompletedAt,
		&i.Error,
		&i.Params,
		&i.Summary,
		&i.DatasetObjectKey,
		&i.PdfObjectKey,
	)
	return i, err
}

const listTaxReportJobs = `-- name: ListTaxReportJobs :many
SELECT
  id, tenant_id, tax_year, jurisdiction, status, requested_at, started_at, completed_at,
  error, params, summary, dataset_object_key, pdf_object_key
FROM tax_report_jobs
WHERE tenant_id = $1 AND ($2 = 0 OR tax_year = $2)
ORDER BY requested_at DESC
LIMIT $3 OFFSET $4
`

type ListTaxReportJobsParams struct {
	TenantID uuid.UUID   `json:"tenantId"`
	Column2  interface{} `json:"column2"`
	Limit    int32       `json:"limit"`
	Offset   int32       `json:"offset"`
}

func (q *Queries) ListTaxReportJobs(ctx context.Context, arg ListTaxReportJobsParams) ([]TaxReportJob, error) {
	rows, err := q.db.Query(ctx, listTaxReportJobs,
		arg.TenantID,
		arg.Column2,
		arg.Limit,
		arg.Offset,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []TaxReportJob
	for rows.Next() {
		var i TaxReportJob
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.TaxYear,
			&i.Jurisdiction,
			&i.Status,
			&i.RequestedAt,
			&i.StartedAt,
			&i.CompletedAt,
			&i.Error,
			&i.Params,
			&i.Summary,
			&i.DatasetObjectKey,
			&i.PdfObjectKey,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markTaxReportJobCompleted = `-- name: MarkTaxReportJobCompleted :exec
UPDATE tax_report_jobs
SET
  status = 'completed',
  completed_at = now(),
  error = NULL,
  pdf_object_key = $2
WHERE id = $1
`

type MarkTaxReportJobCompletedParams struct {
	ID           uuid.UUID `json:"id"`
	PdfObjectKey *string   `json:"pdfObjectKey"`
}

func (q *Queries) MarkTaxReportJobCompleted(ctx context.Context, arg MarkTaxReportJobCompletedParams) error {
	_, err := q.db.Exec(ctx, markTaxReportJobCompleted, arg.ID, arg.PdfObjectKey)
	return err
}

const markTaxReportJobFailed = `-- name: MarkTaxReportJobFailed :exec
UPDATE tax_report_jobs
SET
  status = 'failed',
  completed_at = now(),
  error = $2
WHERE id = $1
`

type MarkTaxReportJobFailedParams struct {
	ID    uuid.UUID `json:"id"`
	Error *string   `json:"error"`
}

func (q *Queries) MarkTaxReportJobFailed(ctx context.Context, arg MarkTaxReportJobFailedParams) error {
	_, err := q.db.Exec(ctx, markTaxReportJobFailed, arg.ID, arg.Error)
	return err
}

const markTaxReportJobProcessing = `-- name: MarkTaxReportJobProcessing :execrows
UPDATE tax_report_jobs
SET status = 'processing', started_at = now(), completed_at = NULL, error = NULL
WHERE id = $1 AND status = 'queued'
`

func (q *Queries) MarkTaxReportJobProcessing(ctx context.Context, id uuid.UUID) (int64, error) {
	result, err := q.db.Exec(ctx, markTaxReportJobProcessing, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const updateTaxReportJobDataset = `-- name: UpdateTaxReportJobDataset :exec
UPDATE tax_report_jobs
SET dataset_object_key = $2, summary = $3
WHERE id = $1
`

type UpdateTaxReportJobDatasetParams struct {
	ID               uuid.UUID `json:"id"`
	DatasetObjectKey *string   `json:"datasetObjectKey"`
	Summary          []byte    `json:"summary"`
}

func (q *Queries) UpdateTaxReportJobDataset(ctx context.Context, arg UpdateTaxReportJobDatasetParams) error {
	_, err := q.db.Exec(ctx, updateTaxReportJobDataset, arg.ID, arg.DatasetObjectKey, arg.Summary)
	return err
}
